# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VacTuzX-dot.Yon
PackageVersion: 0.1.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
# Tauri's NSIS installer registers Apps & Features under the product name.
ProductCode: Yon
ReleaseDate: 2026-09-27
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
AppsAndFeaturesEntries:
- DisplayName: Yon
  ProductCode: Yon
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/VacTuzX-dot/Yon/releases/download/v0.1.1/Yon_0.1.1_x64-setup.exe
  InstallerSha256: 523D501A60B6E58017ADB2BA07DA2E9C4511ACB90B4DBA13EFCCC940F60C4DE4
ManifestType: installer
ManifestVersion: 1.12.0
