#!/usr/bin/env python3
"""Algorithmic soundtrack for the 72 s explainer film (web/film/).

Pure code, standard library only, fixed seeds: the same WAV byte for byte on
every run. No samples, nothing generated by a model. The timeline (scenes,
bpm, cues) is read from web/film/timeline.json, and every cue sound is
scheduled on the exact sample of its cue time.

Key of A: A minor pentatonic for melody, A major for the "whole again" moments
and the ending. At 100 bpm a beat is 0.6 s; all cues in the timeline fall on
the 8th-note-triplet grid (0.2 s), so the rhythm lilts in triplets.

Sections (scene ids from the timeline):
  toss     soft Am9 pad fading in; a noise swell that rises into the first
           `swell` cue and blooms into a mallet A-minor chord (logo assembles);
           a few sparse plucks.
  nearby   pad moves Fmaj9 -> Cadd9 -> G6/9; a sparse Karplus-Strong arpeggio
           in triplets; a sonar "ping" at each `ping` cue (pure tone, echoes
           ping-ponging across the stereo field); the third ping opens into a
           little rising arpeggio as the devices light up.
  send     a soft kick on every beat (the pad ducks gently under it) and a
           plucked bass; at `handshake` two tones glide from opposite sides and
           meet in unison on A; at `stream-start` a stream of quick plucks, each
           group travelling left -> right; at `check` a bright A-major chime.
  folders  fuller: brighter pad, bass, soft triplet ticks; at `stream-start`
           a cascade of falling plucks (runs sweep left -> right); at `check`
           another A-major chime.
  phones   lighter again; at `qr` a short "digital" blip sequence (bit pattern
           like QR modules, panned like a scan line) ending in a two-note
           confirm; from `stream-start` filtered whooshes carry sealed blobs
           left -> right past the relay, each marked by a pluck out and in.
  open     resolve to A major, kick stops, sustained low A; a second swell rises
           into the last `swell` cue (logo returns) with an A-major mallet
           chord; the master fades to silence exactly at the `end` cue.

Signal path: sources mix into three stereo buses (pad, dry, delay send). A
single final pass low-passes and ducks the pad, runs a ping-pong feedback delay
(two triplet 8ths, damped) on the send bus, high-passes the sum at ~30 Hz,
tames the top with a gentle one-pole low-pass, applies the fade, and the whole
thing is normalised to -1.5 dBFS peak.

    python3 scripts/film_music.py web/film/film.wav
"""

import array
import json
import math
import os
import random
import sys
import time

import wave

T_START = time.time()
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(ROOT, "web", "film", "timeline.json"), encoding="utf-8") as fh:
    TL = json.load(fh)

RATE = 44100
DUR = float(TL["duration"])
N = int(round(DUR * RATE))
BEAT = 60.0 / float(TL["bpm"])  # 0.6 s at 100 bpm
TRIP = BEAT / 3  # 8th-note triplet, 0.2 s
BEAT_N = int(round(BEAT * RATE))
SCENE = {s["id"]: s for s in TL["scenes"]}
TAU = 2 * math.pi
sin, cos, exp = math.sin, math.cos, math.exp

# Separate generators so adding a sound in one place never reshuffles another.
rng = random.Random(72)  # musical choices (arp notes, pans, QR bits)
noise_rng = random.Random(11)  # whoosh / swell noise
pad_rng = random.Random(5)  # pad phases and breathing


def cue_times(kind):
    return [float(c["t"]) for c in TL["cues"] if c["kind"] == kind]


def scene_at(t):
    for s in TL["scenes"]:
        if s["start"] <= t < s["end"]:
            return s["id"]
    return TL["scenes"][-1]["id"]


def at(t):
    """Seconds -> sample index (rounded, so a cue lands within half a sample)."""
    return int(round(t * RATE))


def zeros(m):
    return array.array("d", bytes(8 * m))


def mtof(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def smooth(u):
    u = min(max(u, 0.0), 1.0)
    return u * u * (3 - 2 * u)


def pan_gains(p):
    """Equal-power pan, 0 = left ... 1 = right."""
    return cos(p * math.pi / 2), sin(p * math.pi / 2)


def curve(points):
    """Piecewise-linear automation through (time, value) points."""

    def f(t):
        if t <= points[0][0]:
            return points[0][1]
        for (t0, v0), (t1, v1) in zip(points, points[1:]):
            if t <= t1:
                return v0 + (v1 - v0) * (t - t0) / (t1 - t0)
        return points[-1][1]

    return f


# ---------------------------------------------------------------- buses
padL, padR = zeros(N), zeros(N)
dryL, dryR = zeros(N), zeros(N)
sendL, sendR = zeros(N), zeros(N)


def mix(wav, t, gain, pan=0.5, send=0.0):
    """Add a mono waveform at time t with a fixed pan (and delay send)."""
    s = at(t)
    m = min(len(wav), N - s)
    if m <= 0:
        return
    gl, gr = pan_gains(pan)
    gl *= gain
    gr *= gain
    dl, dr = dryL, dryR
    if send:
        sl, sr = gl * send, gr * send
        el, er = sendL, sendR
        for j in range(m):
            v = wav[j]
            n = s + j
            dl[n] += v * gl
            dr[n] += v * gr
            el[n] += v * sl
            er[n] += v * sr
    else:
        for j in range(m):
            v = wav[j]
            n = s + j
            dl[n] += v * gl
            dr[n] += v * gr


def mix_moving(wav, t, gain, pan0, pan1, send=0.0):
    """Like mix(), but the pan travels from pan0 to pan1 (updated every 64 samples)."""
    s = at(t)
    m = min(len(wav), N - s)
    for b0 in range(0, m, 64):
        gl, gr = pan_gains(pan0 + (pan1 - pan0) * smooth(b0 / len(wav)))
        gl *= gain
        gr *= gain
        sl, sr = gl * send, gr * send
        for j in range(b0, min(b0 + 64, m)):
            v = wav[j]
            n = s + j
            dryL[n] += v * gl
            dryR[n] += v * gr
            if send:
                sendL[n] += v * sl
                sendR[n] += v * sr


def fade_edges(w, attack_n=44, release_n=441):
    """Tiny linear fades so no waveform starts or stops with a click."""
    m = len(w)
    for j in range(min(attack_n, m)):
        w[j] *= j / attack_n
    for j in range(min(release_n, m)):
        w[m - 1 - j] *= j / release_n
    return w


# ---------------------------------------------------------------- voices
_cache = {}


def pluck(midi, t60=1.2, bright=0.5):
    """Karplus-Strong string with an all-pass tuning filter (so high notes stay
    in tune), cached per pitch/tone. t60 = seconds to fall 60 dB; bright = how
    much of the noise burst's top end survives the pre-filter."""
    key = ("pluck", midi, t60, bright)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    r = random.Random(1000 + midi * 7 + int(bright * 100))
    total = RATE / f - 0.5  # the two-point average adds half a sample of delay
    P = int(total)
    frac = total - P
    if frac < 0.1:
        P -= 1
        frac += 1
    C = (1 - frac) / (1 + frac)
    loss = 10 ** (-3 / (t60 * f))  # per trip round the loop
    noise = [r.uniform(-1, 1) for _ in range(P)]
    line = [0.0] * P
    s1 = 0.0
    for i in range(2 * P):  # two passes: the filter state wraps round the loop
        s1 += bright * (noise[i % P] - s1)
        line[i % P] = s1
    mean = sum(line) / P
    peak = max(abs(x - mean) for x in line) or 1.0
    line = [(x - mean) / peak for x in line]
    m = int(min(3.0, t60 * 1.05) * RATE)
    out = zeros(m)
    prev = x1 = y1 = 0.0
    k = 0
    for n in range(m):
        s = line[k]
        out[n] = s
        avg = loss * 0.5 * (s + prev)
        prev = s
        y1 = C * avg + x1 - C * y1
        x1 = avg
        line[k] = y1
        k += 1
        if k == P:
            k = 0
    _cache[key] = fade_edges(out, 22, 1323)
    return _cache[key]


def tone(freq, seconds, partials=((1.0, 1.0),), attack=0.005, tau=0.5, glide_to=None, glide_s=0.0):
    """Additive sine tone: partials are (ratio, amplitude); exponential decay tau;
    optional log-frequency glide from freq to glide_to over glide_s seconds."""
    key = ("tone", freq, seconds, partials, attack, tau, glide_to, glide_s)
    if key in _cache:
        return _cache[key]
    m = int(seconds * RATE)
    out = zeros(m)
    ph = 0.0
    inc = TAU * freq / RATE
    ea = 1.0 / max(1, attack * RATE)
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0
    gn = max(1, int(glide_s * RATE))
    ratio = (glide_to / freq) if glide_to else 1.0
    for n in range(m):
        if glide_to and n <= gn:
            inc = TAU * freq * ratio ** smooth(n / gn) / RATE
        v = 0.0
        for r, a in partials:
            v += a * sin(r * ph)
        ph += inc
        out[n] = v * min(1.0, n * ea) * dec
        dec *= ed
    _cache[key] = fade_edges(out, 1, 441)
    return _cache[key]


def noise_sweep(seconds, fmin, fmax, env_fn):
    """Filtered-noise whoosh: white noise through two one-pole low-passes whose
    cutoff follows the envelope (brighter when louder)."""
    m = int(seconds * RATE)
    out = zeros(m)
    s1 = s2 = 0.0
    for n in range(m):
        e = env_fn(n / m)
        a = 1 - exp(-TAU * (fmin + (fmax - fmin) * e) / RATE)
        s1 += a * (noise_rng.uniform(-1, 1) - s1)
        s2 += a * (s1 - s2)
        out[n] = s2 * e
    return fade_edges(out, 44, 441)


def kick_wave():
    """Soft kick: a sine dropping 120 -> 44 Hz with a short round decay."""
    m = int(0.5 * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        t = n / RATE
        ph += TAU * (44 + 76 * exp(-t / 0.03)) / RATE
        out[n] = sin(ph) * min(1.0, n / 88) * exp(-t / 0.17)
    return fade_edges(out, 1, 441)


def tick_wave(seed):
    """Soft 'shaker' tick: band-passed noise (difference of two low-passes)."""
    r = random.Random(seed)
    m = int(0.07 * RATE)
    out = zeros(m)
    a1 = 1 - exp(-TAU * 7000 / RATE)
    a2 = 1 - exp(-TAU * 3000 / RATE)
    s1 = s2 = 0.0
    for n in range(m):
        x = r.uniform(-1, 1)
        s1 += a1 * (x - s1)
        s2 += a2 * (x - s2)
        out[n] = (s1 - s2) * exp(-n / (0.014 * RATE))
    peak = max(abs(v) for v in out) or 1.0
    for n in range(m):
        out[n] /= peak
    return fade_edges(out, 44, 220)


# ---------------------------------------------------------------- harmony
# (bass root, pad voicing) as MIDI numbers.
AM9 = (45, (57, 60, 64, 67, 71))  # A C E G B
FMAJ9 = (41, (53, 60, 64, 67, 69))  # F C E G A
CADD9 = (48, (55, 60, 62, 64, 67))  # G C D E G
G69 = (43, (55, 62, 64, 69, 71))  # G D E A B
GSUS = (43, (55, 60, 62, 67, 69))  # G C D G A
AMAJ = (45, (57, 61, 64, 69, 71))  # A C# E A B
AMAJ_END = (45, (57, 61, 64, 69, 73))  # A C# E A C#

S = {k: (float(v["start"]), float(v["end"])) for k, v in SCENE.items()}
CHECKS = cue_times("check")
PROG = [(0.0, AM9)]
nb = S["nearby"][0]
PROG += [(nb - 0.4, FMAJ9), (nb + 4.4, CADD9), (nb + 9.2, G69)]
PROG += [(cue_times("handshake")[0], AM9), (S["send"][0] + 6.8, FMAJ9)]
PROG += [(CHECKS[0] - 2.4, GSUS), (CHECKS[0] - 0.4, AMAJ)]  # the check lands on A major
fo = S["folders"][0]
PROG += [(fo + 0.4, AM9), (fo + 2.8, FMAJ9), (fo + 5.2, CADD9)]
PROG += [(CHECKS[1] - 1.6, G69), (CHECKS[1] - 0.4, AMAJ)]
ph_ = S["phones"][0]
PROG += [(ph_ + 0.4, AM9), (ph_ + 2.8, FMAJ9), (ph_ + 5.2, CADD9), (ph_ + 7.6, FMAJ9), (ph_ + 10.0, GSUS)]
PROG += [(S["open"][0], AMAJ_END)]  # bVI - bVII - I: the resolution
PROG.sort(key=lambda x: x[0])


def chord_at(t):
    cur = PROG[0][1]
    for t0, ch in PROG:
        if t0 <= t:
            cur = ch
        else:
            break
    return cur


# ---------------------------------------------------------------- pad
XF = 1.2  # crossfade between chords, seconds
PAD_PANS = (0.5, 0.28, 0.72, 0.38, 0.62)
BLK = 256


def render_pad():
    for i, (t0, (_, notes)) in enumerate(PROG):
        first, last = i == 0, i == len(PROG) - 1
        t1 = DUR if last else PROG[i + 1][0]
        a = 0.0 if first else t0 - XF / 2
        b = DUR if last else t1 + XF / 2
        n0, n1 = at(a), min(N, at(b))

        def env(t, first=first, last=last, t0=t0, t1=t1):
            e = 1.0
            if not first:
                e *= sin(math.pi / 2 * min(max((t - t0 + XF / 2) / XF, 0.0), 1.0))
            if not last:
                e *= cos(math.pi / 2 * min(max((t - t1 + XF / 2) / XF, 0.0), 1.0))
            return e

        for v, midi in enumerate(notes):
            inc = TAU * mtof(midi) * (1 + 0.0006 * (v - 2)) / RATE
            ph = pad_rng.uniform(0, TAU)
            vol = 0.11 * (0.7 if v == len(notes) - 1 else 1.0)
            gl, gr = pan_gains(PAD_PANS[v])
            rate = 0.05 + 0.023 * v  # slow breathing, different per voice
            lph = pad_rng.uniform(0, TAU)

            def gain(t, vol=vol, rate=rate, lph=lph, env=env):
                return vol * env(t) * (1 + 0.22 * sin(lph + TAU * rate * t))

            L, R = padL, padR
            g0 = gain(n0 / RATE)
            for b0 in range(n0, n1, BLK):
                b1 = min(b0 + BLK, n1)
                g1 = gain(b1 / RATE)
                dg = (g1 - g0) / (b1 - b0)
                g = g0
                for n in range(b0, b1):
                    s = sin(ph) * g
                    ph += inc
                    g += dg
                    L[n] += s * gl
                    R[n] += s * gr
                g0 = g1


# ---------------------------------------------------------------- parts
def arp(t0, t1, density, lo, hi, gain, t60=1.3, skip=()):
    """Sparse plucked arpeggio on the triplet grid: chord tones, random walk."""
    idx = None
    k = math.ceil(t0 / TRIP - 1e-9)
    while k * TRIP < t1:
        t = k * TRIP
        on_beat = k % 3 == 0
        k += 1
        if any(a <= t < b for a, b in skip):
            continue
        if rng.random() >= density * (1.0 if on_beat else 0.55):
            continue
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(lo, hi + 1) if m % 12 in pcs]
        idx = len(pool) // 2 if idx is None else idx + rng.choice((-2, -1, -1, 1, 1, 2))
        idx = min(max(idx, 0), len(pool) - 1)
        g = gain * (1.0 if on_beat else 0.75) * rng.uniform(0.85, 1.0)
        mix(pluck(pool[idx], t60, 0.45), t, g, rng.uniform(0.3, 0.7), send=0.3)


def swell(t_cue, pre, post, notes, gain, pan_lo=0.25, pan_hi=0.75):
    """Noise rises into t_cue (brightening), then decays; a mallet chord lands on it."""
    peak = pre / (pre + post)

    def env(u):
        if u < peak:
            return (u / peak) ** 2.2
        return exp(-(u - peak) * (pre + post) / (post / 3.5))

    for p0, p1 in ((pan_lo, pan_hi), (pan_hi, pan_lo)):
        w = noise_sweep(pre + post, 180, 2600, env)
        mix_moving(w, t_cue - pre, gain, p0, p1, send=0.25)
    for i, m in enumerate(notes):
        w = tone(mtof(m), 5.0, ((1.0, 1.0), (2.0, 0.12), (3.0, 0.03)), attack=0.004, tau=1.8)
        mix(w, t_cue, 0.085, 0.3 + 0.4 * i / max(1, len(notes) - 1), send=0.3)
    mix(pluck(notes[-1] + 12, 1.6, 0.45), t_cue, 0.1, 0.55, send=0.4)  # a clear accent on the cue


def ping(t, midi, pan, gain=0.16):
    """Sonar ping: near-pure tone, echoes bouncing across the field every 0.4 s."""
    w = tone(mtof(midi), 2.2, ((1.0, 1.0), (2.0, 0.06)), attack=0.003, tau=0.42)
    for k in range(5):
        mix(w, t + k * 2 * TRIP, gain * 0.5 ** k, pan if k % 2 == 0 else 1 - pan, send=0.12)


def handshake(t):
    """Two keys meet: E4 glides up from the left, E5 down from the right, into A4."""
    glide = BEAT
    lo = tone(mtof(64), 2.4, ((1.0, 1.0), (2.0, 0.15)), attack=0.01, tau=1.1, glide_to=mtof(69), glide_s=glide)
    hi = tone(mtof(76), 2.4, ((1.0, 1.0), (2.0, 0.08)), attack=0.01, tau=1.1, glide_to=mtof(69), glide_s=glide)
    mix_moving(lo, t, 0.13, 0.1, 0.5, send=0.2)
    mix_moving(hi, t, 0.10, 0.9, 0.5, send=0.2)
    mix(pluck(64, 0.8, 0.45), t, 0.09, 0.1, send=0.2)  # each key 'arrives' with a pluck
    mix(pluck(76, 0.8, 0.45), t, 0.07, 0.9, send=0.2)
    # they meet: a soft pluck on A and a fifth above
    mix(pluck(81, 1.4, 0.4), t + glide, 0.1, 0.5, send=0.35)
    mix(tone(mtof(76), 2.0, attack=0.02, tau=0.8), t + glide, 0.05, 0.5, send=0.3)


def chime(t, pan, extra=()):
    """'Whole again': bright A-major chime (A5 C#6 E6) over A4."""
    for m in (69, 81, 85, 88) + tuple(extra):
        w = tone(mtof(m), 3.2, ((1.0, 1.0), (2.0, 0.22)), attack=0.004, tau=1.0)
        mix(w, t, 0.08 if m > 70 else 0.06, pan, send=0.35)


def stream(t0, t1, group=6):
    """Chunks leave the left device: groups of quick plucks, each rising in pitch
    and travelling left -> right."""
    k = 0
    while t0 + k * TRIP < t1 - 1e-9:
        t = t0 + k * TRIP
        pos = k % group
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(60, 82) if m % 12 in pcs]
        m = pool[min(len(pool) - 1, pos + (k // group) % 3)]
        pan = 0.12 + 0.76 * pos / (group - 1)
        mix(pluck(m, 0.6, 0.5), t, 0.11 if pos else 0.13, pan, send=0.25)
        k += 1


def cascade(t0, t1, run=8, step=TRIP / 2):
    """The folder unfolds: falling runs of plucks, each run sweeping left -> right."""
    k = 0
    while t0 + k * step < t1 - 1e-9:
        t = t0 + k * step
        pos = k % run
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(57, 86) if m % 12 in pcs]
        top = len(pool) - 1 - (k // run) % 3
        m = pool[max(0, top - pos)]
        pan = 0.15 + 0.7 * pos / (run - 1)
        mix(pluck(m, 0.5, 0.5), t, 0.10 if pos == 0 else 0.07, pan, send=0.3)
        k += 1


def qr(t):
    """QR code forms and is scanned: blips on a 50 ms grid, on/off like QR modules,
    panned like a scan line, then a two-note confirm."""
    steps = 24
    step = BEAT / 12
    notes = (81, 84, 86, 88)  # A5 C6 D6 E6
    for i in range(steps):
        bit = i == 0 or rng.random() < 0.55
        if not bit:
            continue
        m = rng.choice(notes)
        w = tone(mtof(m), 0.09, ((1.0, 1.0), (3.0, 0.12), (5.0, 0.04)), attack=0.002, tau=0.022)
        mix(w, t + i * step, 0.12, 0.2 + 0.6 * i / (steps - 1), send=0.15)
    t_ok = t + steps * step
    for j, m in enumerate((88, 93)):  # E6 -> A6
        w = tone(mtof(m), 0.6, ((1.0, 1.0), (3.0, 0.06)), attack=0.003, tau=0.12)
        mix(w, t_ok + j * TRIP / 2, 0.08, 0.6, send=0.3)


def blobs(t0, t1):
    """Sealed blobs pass the relay: a whoosh left -> right every two beats, with
    a low pluck as each one leaves and a higher one as it lands."""
    k = 0
    while t0 + k * 2 * BEAT < t1 - 1e-9:
        t = t0 + k * 2 * BEAT
        w = noise_sweep(1.1, 300, 2400, lambda u: smooth(u / 0.35) * (1 - smooth((u - 0.45) / 0.55)))
        mix_moving(w, t, 0.12, 0.15, 0.85, send=0.2)
        pcs = {m % 12 for m in chord_at(t)[1]}
        low = [m for m in range(57, 69) if m % 12 in pcs]
        high = [m for m in range(69, 82) if m % 12 in pcs]
        mix(pluck(low[k % len(low)], 1.0, 0.45), t, 0.12, 0.15, send=0.25)
        mix(pluck(high[(k * 2) % len(high)], 0.9, 0.45), t + 4 * TRIP, 0.09, 0.85, send=0.3)
        k += 1


def transition(t_end, gain=0.05, seconds=1.4):
    """Soft reverse whoosh that rises into a scene change."""
    w = noise_sweep(seconds + 0.25, 200, 1800, lambda u, p=seconds / (seconds + 0.25): (u / p) ** 2 if u < p else exp(-(u - p) * 40))
    mix_moving(w, t_end - seconds, gain, 0.35, 0.65, send=0.2)


# ---------------------------------------------------------------- score
render_pad()

# toss: swell into the logo, a few quiet plucks
swell(cue_times("swell")[0], min(0.9, cue_times("swell")[0]), 4.0, (57, 64, 69, 72), 0.10)
arp(4.0, S["toss"][1], 0.12, 64, 79, 0.08)
for tb in (S["nearby"][0], S["send"][0], S["folders"][0], S["phones"][0]):
    transition(tb)

# nearby: arpeggio + sonar pings
pings = cue_times("ping")
arp(S["nearby"][0], S["nearby"][1], 0.35, 64, 79, 0.12, skip=[(p - 0.05, p + 0.25) for p in pings])
for i, p in enumerate(pings):
    ping(p, (76, 81, 81)[min(i, 2)], (0.28, 0.72, 0.5)[min(i, 2)])
ping(pings[-1], 76, 0.5, gain=0.09)  # the third ping is a dyad ...
for j, m in enumerate((76, 81, 84, 88)):  # ... and the devices light up
    mix(pluck(m, 1.2, 0.5), pings[-1] + (j + 1) * TRIP, 0.09, 0.35 + 0.1 * j, send=0.35)

# send: pulse, handshake, stream, check
streams = cue_times("stream-start")
st_send = [t for t in streams if scene_at(t) == "send"][0]
st_fold = [t for t in streams if scene_at(t) == "folders"][0]
st_phone = [t for t in streams if scene_at(t) == "phones"][0]
hs = cue_times("handshake")[0]
handshake(hs)
arp(S["send"][0], st_send, 0.3, 64, 79, 0.1, skip=[(hs - 0.05, hs + 1.2)])
stream(st_send, CHECKS[0] - 2 * TRIP)
chime(CHECKS[0], 0.65)
arp(CHECKS[0] + 2 * TRIP, S["send"][1], 0.25, 64, 79, 0.09)

# the pulse: kick every beat from the send scene until the open scene
KICK = kick_wave()
kick_gain = curve([(S["send"][0], 0.2), (S["send"][0] + 2.4, 0.5), (S["folders"][0], 0.6),
                   (S["phones"][0], 0.45), (S["open"][0], 0.45)])
kb = math.ceil(S["send"][0] / BEAT - 1e-9)
while kb * BEAT < S["open"][0] - 1e-9:
    t = kb * BEAT
    mix(KICK, t, kick_gain(t), 0.5)
    kb += 1

# bass: plucked root on the beat and on the last triplet, from the handshake on
bass_gain = curve([(hs, 0.13), (S["folders"][0], 0.17), (S["phones"][0], 0.13), (S["open"][0], 0.13)])
kb = math.ceil(hs / BEAT - 1e-9)
while kb * BEAT < S["open"][0] - 1e-9:
    t = kb * BEAT
    root = chord_at(t + 0.01)[0]
    w = tone(mtof(root), 0.55, ((1.0, 1.0), (2.0, 0.3), (3.0, 0.06)), attack=0.008, tau=0.28)
    mix(w, t, bass_gain(t), 0.5)
    mix(w, t + 2 * TRIP, bass_gain(t) * 0.45, 0.5)
    kb += 1

# folders: ticks, cascade, check
TICKS = [tick_wave(s) for s in (1, 2, 3)]
kb = math.ceil(S["folders"][0] / TRIP - 1e-9)
while kb * TRIP < S["open"][0] - 1e-9:
    t = kb * TRIP
    slot = kb % 3
    sc = scene_at(t)
    if slot and (sc == "folders" or (sc == "phones" and t >= st_phone and slot == 2)):
        g = (0.035 if slot == 2 else 0.018) * (1.0 if sc == "folders" else 0.6)
        mix(TICKS[kb % 3], t, g, 0.42 if slot == 1 else 0.58)
    kb += 1
arp(S["folders"][0], st_fold, 0.5, 64, 81, 0.1)
cascade(st_fold, CHECKS[1] - 3 * TRIP)
chime(CHECKS[1], 0.7, extra=(76,))
arp(CHECKS[1] + 2 * TRIP, S["folders"][1], 0.4, 64, 81, 0.09)

# phones: QR blips, sealed blobs past the relay
q = cue_times("qr")[0]
arp(S["phones"][0], st_phone, 0.3, 64, 79, 0.09, skip=[(q - 0.1, q + 2.0)])
qr(q)
blobs(st_phone, S["phones"][1] - 0.4)

# open: resolve, low A, logo swell, fade by the end cue
mix(tone(mtof(45), 8.0, ((1.0, 1.0), (2.0, 0.3)), attack=0.06, tau=3.0), S["open"][0], 0.16, 0.5)
end_t = cue_times("end")[0]
sw2 = cue_times("swell")[-1]
arp(S["open"][0] + 2 * TRIP, sw2 - 0.4, 0.3, 69, 84, 0.08)
swell(sw2, 2.0, 5.0, (57, 61, 64, 69, 76), 0.11)
arp(sw2 + 1.0, end_t - 1.5, 0.18, 69, 84, 0.06, t60=1.8)

# ---------------------------------------------------------------- final pass
pad_gain = curve([(0, 0.0), (3.0, 1.0), (S["send"][0], 1.0), (S["send"][0] + 2, 0.9),
                  (S["folders"][0], 1.0), (S["phones"][0], 0.9), (S["open"][0], 1.05)])
pad_cut = curve([(0, 700), (8, 1100), (S["nearby"][0], 1200), (S["send"][0], 1500),
                 (S["folders"][0], 2300), (S["phones"][0], 1700), (S["open"][0], 2200), (DUR, 1500)])
duck_depth = curve([(S["send"][0], 0.0), (S["send"][0] + 2.4, 0.28), (S["folders"][0], 0.38),
                    (S["phones"][0], 0.28), (S["open"][0] - 0.2, 0.28), (S["open"][0] + 0.4, 0.0)])
FADE_S = 4.0


def fade(t):
    if t >= end_t:
        return 0.0
    if t <= end_t - FADE_S:
        return 1.0
    return 0.5 * (1 + cos(math.pi * (t - end_t + FADE_S) / FADE_S))


DUCK = [min(1.0, j / 220) * exp(-j / (0.2 * RATE)) for j in range(BEAT_N)]
D = int(round(2 * TRIP * RATE))  # delay: two triplet 8ths = 0.4 s
FB, WET = 0.36, 0.55
a_damp = 1 - exp(-TAU * 2400 / RATE)
a_top = 1 - exp(-TAU * 11000 / RATE)
R_HP = exp(-TAU * 30 / RATE)
ringL, ringR = zeros(D), zeros(D)
outL, outR = zeros(N), zeros(N)
pl = pr = fl = fr = 0.0
xl1 = xr1 = hl = hr = ml = mr = 0.0
k = 0
for b0 in range(0, N, BLK):
    b1 = min(b0 + BLK, N)
    t = b0 / RATE
    ap = 1 - exp(-TAU * pad_cut(t) / RATE)
    pg = pad_gain(t)
    dd = duck_depth(t)
    fd0, fd1 = fade(t), fade(b1 / RATE)
    dfd = (fd1 - fd0) / (b1 - b0)
    fd = fd0
    j = b0 % BEAT_N
    for n in range(b0, b1):
        pl += ap * (padL[n] - pl)
        pr += ap * (padR[n] - pr)
        g = pg * (1 - dd * DUCK[j])
        j += 1
        if j == BEAT_N:
            j = 0
        wl = ringL[k]
        wr = ringR[k]
        fl += a_damp * (wl - fl)
        fr += a_damp * (wr - fr)
        ringL[k] = sendL[n] + FB * fr  # ping-pong: each side feeds the other
        ringR[k] = sendR[n] + FB * fl
        k += 1
        if k == D:
            k = 0
        xl = pl * g + dryL[n] + WET * wl
        xr = pr * g + dryR[n] + WET * wr
        hl = R_HP * (hl + xl - xl1)
        hr = R_HP * (hr + xr - xr1)
        xl1, xr1 = xl, xr
        ml += a_top * (hl - ml)
        mr += a_top * (hr - mr)
        outL[n] = ml * fd
        outR[n] = mr * fd
        fd += dfd

# Normalise to -1.5 dBFS peak and write 16-bit stereo.
peak = max(max(outL), -min(outL), max(outR), -min(outR)) or 1.0
scale = 10 ** (-1.5 / 20) * 32767 / peak
pcm = array.array("h", bytes(4 * N))
pcm[0::2] = array.array("h", [round(x * scale) for x in outL])
pcm[1::2] = array.array("h", [round(x * scale) for x in outR])
if sys.byteorder == "big":
    pcm.byteswap()
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "web", "film", "film.wav")
with wave.open(out, "wb") as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(RATE)
    w.writeframes(pcm.tobytes())
print(f"wrote {out}: {N / RATE:.3f}s, {RATE} Hz 16-bit stereo, {time.time() - T_START:.1f}s to render")
for c in TL["cues"]:
    print(f"  cue {c['kind']:<12} {c['t']:6.2f}s -> sample {at(c['t'])}")
