#!/usr/bin/env python3
"""Algorithmic soundtrack for the 90 s explainer film (web/film/).

Pure code, standard library only, fixed seeds: the same WAV byte for byte on
every run. No samples, nothing generated by a model. The timeline (scenes,
bpm, cues) is read from web/film/timeline.json, and every cue sound is
scheduled on the exact sample of its cue time.

Key of A: A minor pentatonic for melody, A major for the "whole again" moments
and the ending. At 100 bpm a beat is 0.6 s and a bar 2.4 s; the groove is
anchored on the `groove` cue (21.0 s = beat 35), so its bars fall on
21.0 + 2.4 n and everything lilts on the 8th-note-triplet grid (0.2 s).

Sections (scene ids and cues from the timeline):
  open     room tone: a soft Am9 pad fades in from the `dawn` cue (a slow noise
           and mallet bloom) with three quiet plucks, like morning light.
  problem  wistful room texture (Am9 - Fmaj9 - Dm9 - Em7), a few sparse plucks.
           `think` = a light bubbly pop rising in pitch each time; `nope` = a
           soft, slightly comic, descending "bwomp-bwomp".
  friend   `buzz` = two short low rattles of a phone on a wooden desk; `chat` =
           a friendly two-note message chime; `whoosh` = noise and a sine riser
           as the camera dives into the screen; `wipe` = a glittery, bit-crushed
           pixel sparkle rising into the island.
  groove   from `groove` (21.0) to the second `wipe` (66.0): soft sine kick,
           noise hats and snare on the triplet shuffle, triangle-wave chip bass,
           a thin 12.5% pulse arpeggio, and a 25% pulse lead that is doubled by
           a Karplus-Strong pluck so it stays warm. The pad follows Am - F - C - G
           one chord per bar and ducks under the kick. Layers enter bar by bar:
             nearby   (21-31) kick, hats, bass, arpeggio; sonar `ping`s echo
                      across the stereo field and the third opens into a rising
                      arpeggio; the lead enters on the bar before `send`.
             send     (31-46) full beat; `handshake` two tones glide in from
                      opposite sides and meet on A; `lock` a click and a clunk;
                      `stream-start` quick plucks travelling left -> right; the
                      `check` lands on an A-major chime and chord.
             folders  (46-55) `chest` creak, thunk and sparkle; a cascade of
                      falling plucks sweeping left -> right; `check` chime.
             phones   (55-66) the beat thins out for `qr` (digital blips like QR
                      modules) and `scan` (a sweep that ends in a two-note
                      confirm); `relay` whooshes of sealed packets pass a tower
                      left -> right, each marked with plucks; the last `check`
                      holds A major into a snare roll and a crash on the wipe.
  decide   back in the room (`wipe` sparkle falls, `calm` = the beat has stopped:
           low A and a soft settling chord); `dialog` a soft UI pop; `click` a
           mouse click (down and up); `stream-start` a short toss, an arc of
           quick plucks L -> R; `check` chime; `jump` a rising "boing"; `chat`
           (from "me") a rising message-sent swoosh, unlike the received chime.
  outro    `whoosh` flies out of the window; `build` logo blocks land as ticks
           that accelerate up an A minor pentatonic ladder under a rising noise
           swell; `swell` a big warm A-major chord; sparse shimmer, then the
           master fades from `end` (88.0 s) to silence exactly at 90.0 s.

Signal path: sources mix into three stereo buses (pad, dry, delay send). A
single final pass low-passes and ducks the pad, runs a ping-pong feedback delay
(two triplet 8ths, damped) on the send bus, high-passes the sum at ~30 Hz,
tames the top with a gentle one-pole low-pass, applies the fade, and the whole
thing is normalised to -1.5 dBFS peak.

    python3 scripts/film_music.py web/film/film.wav
"""

import array
import json
import math
import os
import random
import sys
import time

import wave

T_START = time.time()
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(ROOT, "web", "film", "timeline.json"), encoding="utf-8") as fh:
    TL = json.load(fh)

RATE = 44100
DUR = float(TL["duration"])
N = int(round(DUR * RATE))
BEAT = 60.0 / float(TL["bpm"])  # 0.6 s at 100 bpm
TRIP = BEAT / 3  # 8th-note triplet, 0.2 s
BAR = 4 * BEAT  # 2.4 s
BEAT_N = int(round(BEAT * RATE))
SCENE = {s["id"]: s for s in TL["scenes"]}
TAU = 2 * math.pi
sin, cos, exp = math.sin, math.cos, math.exp

# Separate generators so adding a sound in one place never reshuffles another.
rng = random.Random(90)  # musical choices (arp notes, pans, QR bits)
noise_rng = random.Random(11)  # whoosh / swell noise
pad_rng = random.Random(5)  # pad phases and breathing
fx_rng = random.Random(33)  # sparkle / crackle choices


def cue_times(kind):
    return [float(c["t"]) for c in TL["cues"] if c["kind"] == kind]


def at(t):
    """Seconds -> sample index (rounded, so a cue lands within half a sample)."""
    return int(round(t * RATE))


def zeros(m):
    return array.array("d", bytes(8 * m))


def mtof(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def smooth(u):
    u = min(max(u, 0.0), 1.0)
    return u * u * (3 - 2 * u)


def pan_gains(p):
    """Equal-power pan, 0 = left ... 1 = right."""
    return cos(p * math.pi / 2), sin(p * math.pi / 2)


def curve(points):
    """Piecewise-linear automation through (time, value) points."""

    def f(t):
        if t <= points[0][0]:
            return points[0][1]
        for (t0, v0), (t1, v1) in zip(points, points[1:]):
            if t <= t1:
                return v0 + (v1 - v0) * (t - t0) / (t1 - t0)
        return points[-1][1]

    return f


def in_any(windows, t):
    return any(a <= t < b for a, b in windows)


# Key moments from the timeline.
G0 = cue_times("groove")[0]  # the beat starts (21.0)
WIPES = cue_times("wipe")
GEND = WIPES[-1]  # the groove ends on the second pixel wipe (66.0)
CALM = cue_times("calm")[0]
END_T = cue_times("end")[0]
CHK = cue_times("check")
CHAT_FROM = {round(float(c["t"]), 3): c["from"] for c in TL["chat"]}
NBARS = int(math.ceil((GEND - G0) / BAR - 1e-9))  # 19, the last one is partial
S = {k: (float(v["start"]), float(v["end"])) for k, v in SCENE.items()}


# ---------------------------------------------------------------- buses
padL, padR = zeros(N), zeros(N)
dryL, dryR = zeros(N), zeros(N)
sendL, sendR = zeros(N), zeros(N)


def mix(wav, t, gain, pan=0.5, send=0.0):
    """Add a mono waveform at time t with a fixed pan (and delay send)."""
    s = at(t)
    m = min(len(wav), N - s)
    if m <= 0:
        return
    gl, gr = pan_gains(pan)
    gl *= gain
    gr *= gain
    dl, dr = dryL, dryR
    if send:
        sl, sr = gl * send, gr * send
        el, er = sendL, sendR
        for j in range(m):
            v = wav[j]
            n = s + j
            dl[n] += v * gl
            dr[n] += v * gr
            el[n] += v * sl
            er[n] += v * sr
    else:
        for j in range(m):
            v = wav[j]
            n = s + j
            dl[n] += v * gl
            dr[n] += v * gr


def mix_moving(wav, t, gain, pan0, pan1, send=0.0):
    """Like mix(), but the pan travels from pan0 to pan1 (updated every 64 samples)."""
    s = at(t)
    m = min(len(wav), N - s)
    for b0 in range(0, m, 64):
        gl, gr = pan_gains(pan0 + (pan1 - pan0) * smooth(b0 / len(wav)))
        gl *= gain
        gr *= gain
        sl, sr = gl * send, gr * send
        for j in range(b0, min(b0 + 64, m)):
            v = wav[j]
            n = s + j
            dryL[n] += v * gl
            dryR[n] += v * gr
            if send:
                sendL[n] += v * sl
                sendR[n] += v * sr


def fade_edges(w, attack_n=44, release_n=441):
    """Tiny linear fades so no waveform starts or stops with a click."""
    m = len(w)
    for j in range(min(attack_n, m)):
        w[j] *= j / attack_n
    for j in range(min(release_n, m)):
        w[m - 1 - j] *= j / release_n
    return w


def peak_normalise(w):
    peak = max(max(w), -min(w)) or 1.0
    for n in range(len(w)):
        w[n] /= peak
    return w


# ---------------------------------------------------------------- voices
_cache = {}


def pluck(midi, t60=1.2, bright=0.5):
    """Karplus-Strong string with an all-pass tuning filter (so high notes stay
    in tune), cached per pitch/tone. t60 = seconds to fall 60 dB; bright = how
    much of the noise burst's top end survives the pre-filter."""
    key = ("pluck", midi, t60, bright)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    r = random.Random(1000 + midi * 7 + int(bright * 100))
    total = RATE / f - 0.5  # the two-point average adds half a sample of delay
    P = int(total)
    frac = total - P
    if frac < 0.1:
        P -= 1
        frac += 1
    C = (1 - frac) / (1 + frac)
    loss = 10 ** (-3 / (t60 * f))  # per trip round the loop
    noise = [r.uniform(-1, 1) for _ in range(P)]
    line = [0.0] * P
    s1 = 0.0
    for i in range(2 * P):  # two passes: the filter state wraps round the loop
        s1 += bright * (noise[i % P] - s1)
        line[i % P] = s1
    mean = sum(line) / P
    peak = max(abs(x - mean) for x in line) or 1.0
    line = [(x - mean) / peak for x in line]
    m = int(min(3.0, t60 * 1.05) * RATE)
    out = zeros(m)
    prev = x1 = y1 = 0.0
    k = 0
    for n in range(m):
        s = line[k]
        out[n] = s
        avg = loss * 0.5 * (s + prev)
        prev = s
        y1 = C * avg + x1 - C * y1
        x1 = avg
        line[k] = y1
        k += 1
        if k == P:
            k = 0
    _cache[key] = fade_edges(out, 22, 1323)
    return _cache[key]


def tone(freq, seconds, partials=((1.0, 1.0),), attack=0.005, tau=0.5, glide_to=None, glide_s=0.0):
    """Additive sine tone: partials are (ratio, amplitude); exponential decay tau;
    optional log-frequency glide from freq to glide_to over glide_s seconds."""
    key = ("tone", freq, seconds, partials, attack, tau, glide_to, glide_s)
    if key in _cache:
        return _cache[key]
    m = int(seconds * RATE)
    out = zeros(m)
    ph = 0.0
    inc = TAU * freq / RATE
    ea = 1.0 / max(1, attack * RATE)
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0
    gn = max(1, int(glide_s * RATE))
    ratio = (glide_to / freq) if glide_to else 1.0
    for n in range(m):
        if glide_to and n <= gn:
            inc = TAU * freq * ratio ** smooth(n / gn) / RATE
        v = 0.0
        for r, a in partials:
            v += a * sin(r * ph)
        ph += inc
        out[n] = v * min(1.0, n * ea) * dec
        dec *= ed
    _cache[key] = fade_edges(out, 1, 441)
    return _cache[key]


def noise_sweep(seconds, fmin, fmax, env_fn):
    """Filtered-noise whoosh: white noise through two one-pole low-passes whose
    cutoff follows the envelope (brighter when louder)."""
    m = int(seconds * RATE)
    out = zeros(m)
    s1 = s2 = 0.0
    for n in range(m):
        e = env_fn(n / m)
        a = 1 - exp(-TAU * (fmin + (fmax - fmin) * e) / RATE)
        s1 += a * (noise_rng.uniform(-1, 1) - s1)
        s2 += a * (s1 - s2)
        out[n] = s2 * e
    return fade_edges(out, 44, 441)


def kick_wave():
    """Soft kick: a sine dropping 120 -> 44 Hz with a short round decay."""
    m = int(0.5 * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        t = n / RATE
        ph += TAU * (44 + 76 * exp(-t / 0.03)) / RATE
        out[n] = sin(ph) * min(1.0, n / 88) * exp(-t / 0.17)
    return fade_edges(out, 1, 441)


def hat_wave(seed, seconds, tau, hp=6000):
    """Noise hat: white noise minus its own low-pass (a high-pass at hp Hz)."""
    r = random.Random(seed)
    m = int(seconds * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * hp / RATE)
    lp = 0.0
    for n in range(m):
        x = r.uniform(-1, 1)
        lp += a * (x - lp)
        out[n] = (x - lp) * exp(-n / (tau * RATE))
    return fade_edges(peak_normalise(out), 22, 220)


def snare_wave():
    """Soft snare: high-passed noise plus a short falling sine body."""
    r = random.Random(41)
    m = int(0.3 * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * 1800 / RATE)
    lp = ph = 0.0
    for n in range(m):
        t = n / RATE
        x = r.uniform(-1, 1)
        lp += a * (x - lp)
        ph += TAU * (160 + 110 * exp(-t / 0.02)) / RATE
        out[n] = (x - lp) * 0.7 * exp(-t / 0.065) + sin(ph) * 0.6 * exp(-t / 0.05)
    return fade_edges(peak_normalise(out), 22, 441)


def pulse_table(f, duty, size=1024):
    """One cycle of a band-limited pulse wave (harmonics up to ~8 kHz, gently
    rolled off), as a wavetable with a guard sample."""
    key = ("pt", round(f, 3), duty)
    if key in _cache:
        return _cache[key]
    H = max(1, int(8000 / f))
    amps = [(2 / (math.pi * h)) * sin(math.pi * h * duty) / (1 + (h * f / 6000) ** 2) for h in range(1, H + 1)]
    tab = [0.0] * (size + 1)
    for i in range(size):
        th = TAU * i / size
        tab[i] = sum(a * cos((h + 1) * th) for h, a in enumerate(amps))
    tab[size] = tab[0]
    peak = max(abs(v) for v in tab) or 1.0
    tab = [v / peak for v in tab]
    _cache[key] = tab
    return tab


def chip(midi, seconds, duty=0.25, tau=0.3, attack=0.004, vib=0.0):
    """Chiptune-style pulse voice (band-limited so it never aliases harshly):
    exponential decay, optional delayed vibrato."""
    key = ("chip", midi, seconds, duty, tau, attack, vib)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    tab = pulse_table(f, duty)
    size = len(tab) - 1
    m = int(seconds * RATE)
    out = zeros(m)
    p = 0.0
    inc = f / RATE
    ea = 1.0 / max(1, attack * RATE)
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0
    vd = int(0.12 * RATE)
    vr = int(0.25 * RATE)
    for n in range(m):
        if vib and n > vd:
            inc = f * (1 + vib * min(1.0, (n - vd) / vr) * sin(TAU * 5.6 * (n - vd) / RATE)) / RATE
        x = p * size
        i = int(x)
        v = tab[i] + (tab[i + 1] - tab[i]) * (x - i)
        p += inc
        if p >= 1.0:
            p -= 1.0
        out[n] = v * min(1.0, n * ea) * dec
        dec *= ed
    _cache[key] = fade_edges(out, 1, 441)
    return _cache[key]


def tri_wave(midi, seconds, tau=0.2, attack=0.004):
    """Triangle voice for the chip bass."""
    key = ("tri", midi, seconds, tau, attack)
    if key in _cache:
        return _cache[key]
    m = int(seconds * RATE)
    out = zeros(m)
    inc = mtof(midi) / RATE
    p = 0.25  # start at the zero crossing
    ea = 1.0 / max(1, attack * RATE)
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0
    for n in range(m):
        out[n] = (4 * abs(p - 0.5) - 1) * min(1.0, n * ea) * dec
        p += inc
        if p >= 1.0:
            p -= 1.0
        dec *= ed
    _cache[key] = fade_edges(out, 1, 441)
    return _cache[key]


def crush(w, hold=4, bits=4):
    """Bit-crusher: sample-and-hold every `hold` samples, quantised to `bits`."""
    lv = 2 ** (bits - 1)
    out = zeros(len(w))
    v = 0.0
    for j in range(len(w)):
        if j % hold == 0:
            v = round(w[j] * lv) / lv
        out[j] = v
    return fade_edges(out, 1, 220)


# ---------------------------------------------------------------- harmony
# (bass root, pad voicing) as MIDI numbers.
AM9 = (45, (57, 60, 64, 67, 71))  # A C E G B
FMAJ9 = (41, (53, 60, 64, 67, 69))  # F C E G A
CADD9 = (48, (55, 60, 62, 64, 67))  # G C D E G
G69 = (43, (55, 62, 64, 69, 71))  # G D E A B
DM9 = (38, (53, 57, 60, 62, 64))  # F A C D E (root in the bass)
EM7 = (40, (55, 59, 62, 64, 67))  # G B D E G (root in the bass)
AMAJ = (45, (57, 61, 64, 69, 71))  # A C# E A B
AMAJ_END = (45, (57, 61, 64, 69, 73))  # A C# E A C#
MINOR = (AM9, DM9, EM7)
CYCLE = [AM9, FMAJ9, CADD9, G69]  # one chord per bar in the groove

ROOM = [  # (time, chord) outside the groove
    (0.0, AM9), (4.0, FMAJ9), (6.8, DM9), (9.6, EM7), (12.8, CADD9), (15.6, FMAJ9), (18.0, G69),
    (GEND, AM9), (68.3, FMAJ9), (70.4, CADD9), (72.8, AMAJ), (76.8, G69),
    (79.0, FMAJ9), (81.0, CADD9), (82.6, G69), (84.0, AMAJ_END),
]


def next_bar(t):
    return G0 + BAR * (math.floor((t - G0) / BAR + 1e-9) + 1)


# Each groove `check` turns the bar into A major (the "whole again" colour);
# the last one holds until the groove ends.
OVR = []
_grv_checks = [c for c in CHK if G0 < c < GEND]
for _c in _grv_checks:
    OVR.append((_c - 0.2, GEND if _c == _grv_checks[-1] else next_bar(_c + 0.3)))


def chord_at(t):
    if G0 <= t < GEND:
        if in_any(OVR, t):
            return AMAJ
        return CYCLE[int((t - G0) // BAR) % 4]
    cur = ROOM[0][1]
    for t0, ch in ROOM:
        if t0 <= t:
            cur = ch
        else:
            break
    return cur


_pts = {t for t, _ in ROOM}
_pts |= {G0 + BAR * b for b in range(NBARS)}
for _a, _b in OVR:
    _pts |= {_a, _b}
PROG = []  # (time, chord, crossfade seconds)
for _t in sorted(_pts):
    _ch = chord_at(_t + 1e-6)
    if PROG and PROG[-1][1] is _ch:
        continue
    PROG.append((_t, _ch, 0.0 if not PROG else (0.4 if G0 <= _t < GEND else 1.4)))


# ---------------------------------------------------------------- pad
PAD_PANS = (0.5, 0.28, 0.72, 0.38, 0.62)
BLK = 256


def render_pad():
    for i, (t0, (_, notes), xf0) in enumerate(PROG):
        first, last = i == 0, i == len(PROG) - 1
        t1 = DUR if last else PROG[i + 1][0]
        xf1 = 0.0 if last else PROG[i + 1][2]
        a = 0.0 if first else t0 - xf0 / 2
        b = DUR if last else t1 + xf1 / 2
        n0, n1 = at(a), min(N, at(b))

        def env(t, first=first, last=last, t0=t0, t1=t1, xf0=xf0, xf1=xf1):
            e = 1.0
            if not first:
                e *= sin(math.pi / 2 * min(max((t - t0 + xf0 / 2) / xf0, 0.0), 1.0))
            if not last:
                e *= cos(math.pi / 2 * min(max((t - t1 + xf1 / 2) / xf1, 0.0), 1.0))
            return e

        for v, midi in enumerate(notes):
            inc = TAU * mtof(midi) * (1 + 0.0006 * (v - 2)) / RATE
            ph = pad_rng.uniform(0, TAU)
            vol = 0.11 * (0.7 if v == len(notes) - 1 else 1.0)
            gl, gr = pan_gains(PAD_PANS[v])
            rate = 0.05 + 0.023 * v  # slow breathing, different per voice
            lph = pad_rng.uniform(0, TAU)

            def gain(t, vol=vol, rate=rate, lph=lph, env=env):
                return vol * env(t) * (1 + 0.22 * sin(lph + TAU * rate * t))

            L, R = padL, padR
            g0 = gain(n0 / RATE)
            for b0 in range(n0, n1, BLK):
                b1 = min(b0 + BLK, n1)
                g1 = gain(b1 / RATE)
                dg = (g1 - g0) / (b1 - b0)
                g = g0
                for n in range(b0, b1):
                    s = sin(ph) * g
                    ph += inc
                    g += dg
                    L[n] += s * gl
                    R[n] += s * gr
                g0 = g1


# ---------------------------------------------------------------- parts
def arp(t0, t1, density, lo, hi, gain, t60=1.3, skip=()):
    """Sparse plucked arpeggio on the triplet grid: chord tones, random walk."""
    idx = None
    k = math.ceil(t0 / TRIP - 1e-9)
    while k * TRIP < t1:
        t = k * TRIP
        on_beat = k % 3 == 0
        k += 1
        if in_any(skip, t):
            continue
        if rng.random() >= density * (1.0 if on_beat else 0.55):
            continue
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(lo, hi + 1) if m % 12 in pcs]
        idx = len(pool) // 2 if idx is None else idx + rng.choice((-2, -1, -1, 1, 1, 2))
        idx = min(max(idx, 0), len(pool) - 1)
        g = gain * (1.0 if on_beat else 0.75) * rng.uniform(0.85, 1.0)
        mix(pluck(pool[idx], t60, 0.45), t, g, rng.uniform(0.3, 0.7), send=0.3)


def swell(t_cue, pre, post, notes, gain, pan_lo=0.25, pan_hi=0.75):
    """Noise rises into t_cue (brightening), then decays; a mallet chord lands on it."""
    peak = pre / (pre + post)

    def env(u):
        if u < peak:
            return (u / peak) ** 2.2
        return exp(-(u - peak) * (pre + post) / (post / 3.5))

    for p0, p1 in ((pan_lo, pan_hi), (pan_hi, pan_lo)):
        w = noise_sweep(pre + post, 180, 2600, env)
        mix_moving(w, t_cue - pre, gain, p0, p1, send=0.25)
    for i, m in enumerate(notes):
        w = tone(mtof(m), 5.0, ((1.0, 1.0), (2.0, 0.12), (3.0, 0.03)), attack=0.004, tau=1.8)
        mix(w, t_cue, 0.085, 0.3 + 0.4 * i / max(1, len(notes) - 1), send=0.3)
    mix(pluck(notes[-1] + 12, 1.6, 0.45), t_cue, 0.1, 0.55, send=0.4)  # a clear accent on the cue


def ping(t, midi, pan, gain=0.27):
    """Sonar ping: near-pure tone, echoes bouncing across the field every 0.4 s."""
    w = tone(mtof(midi), 2.2, ((1.0, 1.0), (2.0, 0.06)), attack=0.003, tau=0.42)
    for k in range(5):
        mix(w, t + k * 2 * TRIP, gain * 0.5 ** k, pan if k % 2 == 0 else 1 - pan, send=0.12)


def handshake(t):
    """Two keys meet: E4 glides up from the left, E5 down from the right, into A4."""
    glide = BEAT
    lo = tone(mtof(64), 2.4, ((1.0, 1.0), (2.0, 0.15)), attack=0.01, tau=1.1, glide_to=mtof(69), glide_s=glide)
    hi = tone(mtof(76), 2.4, ((1.0, 1.0), (2.0, 0.08)), attack=0.01, tau=1.1, glide_to=mtof(69), glide_s=glide)
    mix_moving(lo, t, 0.22, 0.1, 0.5, send=0.2)
    mix_moving(hi, t, 0.17, 0.9, 0.5, send=0.2)
    mix(pluck(64, 0.8, 0.45), t, 0.15, 0.1, send=0.2)  # each key 'arrives' with a pluck
    mix(pluck(76, 0.8, 0.45), t, 0.12, 0.9, send=0.2)
    # they meet: a soft pluck on A and a fifth above
    mix(pluck(81, 1.4, 0.4), t + glide, 0.16, 0.5, send=0.35)
    mix(tone(mtof(76), 2.0, attack=0.02, tau=0.8), t + glide, 0.05, 0.5, send=0.3)


def lock(t):
    """TLS lock closes: a bright click, a short metal ting and a low clunk."""
    mix(hat_wave(91, 0.03, 0.006, 2500), t, 0.4, 0.5)
    mix(tone(1250, 0.16, ((1.0, 1.0), (2.4, 0.5), (5.1, 0.2)), attack=0.001, tau=0.035), t, 0.1, 0.5, send=0.15)
    mix(tone(mtof(40), 0.25, ((1.0, 1.0), (2.0, 0.35), (3.0, 0.1)), attack=0.002, tau=0.06,
             glide_to=mtof(33), glide_s=0.05), t + 0.035, 0.5, 0.5)


def chime(t, pan, extra=(), scale=1.0):
    """'Whole again': bright A-major chime (A5 C#6 E6) over A4."""
    for m in (69, 81, 85, 88) + tuple(extra):
        w = tone(mtof(m), 3.2, ((1.0, 1.0), (2.0, 0.22)), attack=0.004, tau=1.0)
        mix(w, t, (0.08 if m > 70 else 0.06) * scale, pan, send=0.35)


def stream(t0, t1, group=6):
    """Chunks leave the left device: groups of quick plucks, each rising in pitch
    and travelling left -> right."""
    k = 0
    while t0 + k * TRIP < t1 - 1e-9:
        t = t0 + k * TRIP
        pos = k % group
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(60, 82) if m % 12 in pcs]
        m = pool[min(len(pool) - 1, pos + (k // group) % 3)]
        pan = 0.12 + 0.76 * pos / (group - 1)
        mix(pluck(m, 0.6, 0.5), t, 0.21 if pos else 0.25, pan, send=0.25)
        k += 1


def cascade(t0, t1, run=8, step=TRIP / 2):
    """The folder unfolds: falling runs of plucks, each run sweeping left -> right."""
    k = 0
    while t0 + k * step < t1 - 1e-9:
        t = t0 + k * step
        pos = k % run
        pcs = {m % 12 for m in chord_at(t)[1]}
        pool = [m for m in range(57, 86) if m % 12 in pcs]
        top = len(pool) - 1 - (k // run) % 3
        m = pool[max(0, top - pos)]
        pan = 0.15 + 0.7 * pos / (run - 1)
        mix(pluck(m, 0.5, 0.5), t, 0.21 if pos == 0 else 0.15, pan, send=0.3)
        k += 1


def toss(t0, seconds=2.5, step=0.1):
    """A short toss across the room: quick plucks L -> R climbing to an apex and
    falling again, like the arc of a thrown file."""
    pool = [m for m in range(64, 89) if m % 12 in (9, 0, 2, 4, 7)]  # A minor pentatonic
    n = int(seconds / step)
    half = (n - 1) / 2
    for k in range(n):
        arc = 1 - ((k - half) / half) ** 2
        m = pool[min(len(pool) - 1, int(round(arc * (len(pool) - 1) * 0.8)))]
        mix(pluck(m, 0.5, 0.5), t0 + k * step, 0.17 if k == 0 else 0.125, 0.12 + 0.76 * k / (n - 1), send=0.25)


def qr(t, seconds=1.0):
    """QR code forms on the floor: blips on a 50 ms grid, on/off like QR modules,
    panned like a scan line."""
    steps = int(round(seconds / 0.05))
    notes = (81, 84, 86, 88)  # A5 C6 D6 E6
    for i in range(steps):
        bit = i == 0 or rng.random() < 0.55
        if not bit:
            continue
        m = rng.choice(notes)
        w = tone(mtof(m), 0.09, ((1.0, 1.0), (3.0, 0.12), (5.0, 0.04)), attack=0.002, tau=0.022)
        mix(w, t + i * 0.05, 0.22, 0.2 + 0.6 * i / (steps - 1), send=0.15)


def scan(t):
    """The phone scans the code: a rising sweep travelling across the field,
    ending in a two-note confirm."""
    w = tone(300.0, 0.9, ((1.0, 1.0), (3.0, 0.15)), attack=0.05, tau=30.0, glide_to=1800.0, glide_s=0.85)
    mix_moving(w, t, 0.14, 0.1, 0.9, send=0.2)
    for j, m in enumerate((88, 93)):  # E6 -> A6
        mix(tone(mtof(m), 0.6, ((1.0, 1.0), (3.0, 0.06)), attack=0.003, tau=0.12), t + 1.0 + j * TRIP * 0.7, 0.16, 0.6, send=0.3)


def blobs(t0, t1):
    """Sealed packets pass the relay tower: a whoosh left -> right every two
    beats; a low pluck as each leaves, a bell tone as it passes the tower in the
    middle and a higher pluck as it lands."""
    k = 0
    while t0 + k * 2 * BEAT < t1 - 1e-9:
        t = t0 + k * 2 * BEAT
        w = noise_sweep(1.1, 300, 2400, lambda u: smooth(u / 0.35) * (1 - smooth((u - 0.45) / 0.55)))
        mix_moving(w, t, 0.2, 0.15, 0.85, send=0.2)
        pcs = {m % 12 for m in chord_at(t)[1]}
        low = [m for m in range(57, 69) if m % 12 in pcs]
        high = [m for m in range(69, 82) if m % 12 in pcs]
        mix(pluck(low[k % len(low)], 1.0, 0.45), t, 0.19, 0.15, send=0.25)
        mix(tone(mtof(76), 0.7, ((1.0, 1.0), (2.76, 0.15)), attack=0.003, tau=0.2), t + 0.5, 0.08, 0.5, send=0.3)
        mix(pluck(high[(k * 2) % len(high)], 0.9, 0.45), t + 4 * TRIP, 0.15, 0.85, send=0.3)
        k += 1


def transition(t_end, gain=0.05, seconds=1.4):
    """Soft reverse whoosh that rises into a scene change."""
    w = noise_sweep(seconds + 0.25, 200, 1800, lambda u, p=seconds / (seconds + 0.25): (u / p) ** 2 if u < p else exp(-(u - p) * 40))
    mix_moving(w, t_end - seconds, gain, 0.35, 0.65, send=0.2)


# ---- room and effect sounds
def dawn(t):
    """Morning light: a slow noise breath and a mallet chord that fade in."""
    w = noise_sweep(3.4, 90, 800, lambda u: smooth(u) ** 1.5 * (1 - smooth((u - 0.85) / 0.15)))
    mix_moving(w, t, 0.05, 0.3, 0.7, send=0.2)
    for i, m in enumerate((57, 64, 69, 71)):
        mix(tone(mtof(m), 4.0, ((1.0, 1.0), (2.0, 0.1)), attack=1.4, tau=1.6), t, 0.05, 0.3 + 0.13 * i, send=0.3)


def think(t, i):
    """A thought bubble pops: a quick upward sine blip, higher each time."""
    base = (72, 76, 79)[i % 3]
    w = tone(mtof(base - 5), 0.3, ((1.0, 1.0), (2.0, 0.3)), attack=0.004, tau=0.07, glide_to=mtof(base + 7), glide_s=0.07)
    pan = (0.3, 0.5, 0.7)[i % 3]
    mix(w, t, 0.3, pan, send=0.25)
    mix(tone(mtof(base + 12), 0.2, attack=0.002, tau=0.05), t + 0.085, 0.08, pan, send=0.3)


def nope(t):
    """Idea crossed out: a soft, slightly comic descending 'bwomp-bwomp'."""
    parts = ((1.0, 1.0), (2.0, 0.6), (3.0, 0.25), (4.0, 0.1))
    mix(tone(196.0, 0.5, parts, attack=0.012, tau=0.16, glide_to=147.0, glide_s=0.22), t, 0.22, 0.5, send=0.15)
    mix(tone(165.0, 0.7, parts, attack=0.012, tau=0.22, glide_to=104.0, glide_s=0.4), t + 0.22, 0.22, 0.5, send=0.15)


def buzz(t):
    """Phone vibrating on a wooden desk: two short pulses of a low buzz, a
    band-passed rattle, and a knock at the start of each pulse."""
    r = random.Random(131)
    m = int(0.64 * RATE)
    car = zeros(m)
    rat = zeros(m)
    a1 = 1 - exp(-TAU * 1300 / RATE)
    a2 = 1 - exp(-TAU * 260 / RATE)
    lp1 = lp2 = ph = 0.0

    def pulse(tt, a, b):
        return smooth((tt - a) / 0.01) * (1 - smooth((tt - b + 0.03) / 0.03))

    for n in range(m):
        tt = n / RATE
        e = pulse(tt, 0.0, 0.24) + pulse(tt, 0.34, 0.58)
        am = 0.55 + 0.45 * sin(TAU * 52 * tt)  # the vibration itself
        x = r.uniform(-1, 1)
        lp1 += a1 * (x - lp1)
        lp2 += a2 * (x - lp2)
        ph += TAU * (96 + 6 * sin(TAU * 9 * tt)) / RATE
        saw = sum(sin(h * ph) / h for h in range(1, 7))
        knock = 0.0
        for t0 in (0.0, 0.34):
            if tt >= t0:
                knock += sin(TAU * 170 * tt) * exp(-(tt - t0) / 0.02)
        car[n] = e * (am * saw * 0.5 + knock * 0.9)
        rat[n] = e * am * (lp1 - lp2)
    peak_normalise(car)
    peak_normalise(rat)
    out = zeros(m)
    for n in range(m):
        out[n] = 0.65 * car[n] + 0.45 * rat[n]
    fade_edges(peak_normalise(out), 22, 441)
    mix(out, t, 0.42, 0.4, send=0.1)


def msg_in(t):
    """Message received: a friendly two-note bell."""
    for j, m in enumerate((88, 93)):  # E6 A6
        w = tone(mtof(m), 1.4, ((1.0, 1.0), (2.0, 0.2), (3.0, 0.06)), attack=0.003, tau=0.3)
        mix(w, t + j * 0.13, 0.2, 0.62, send=0.3)
    mix(pluck(76, 0.7, 0.4), t, 0.1, 0.6, send=0.2)


def msg_out(t):
    """Message sent: a rising noise swoosh and a gliding sine, left -> right."""
    w = noise_sweep(0.5, 400, 4500, lambda u: smooth(u / 0.7) * (1 - smooth((u - 0.7) / 0.3)))
    mix_moving(w, t, 0.25, 0.3, 0.85, send=0.2)
    g = tone(mtof(76), 0.4, ((1.0, 1.0), (2.0, 0.15)), attack=0.01, tau=0.14, glide_to=mtof(88), glide_s=0.22)
    mix_moving(g, t, 0.15, 0.35, 0.8, send=0.25)


def whoosh(t, seconds, lo, hi, peak, gain):
    """Camera move: filtered noise that swells to `peak` (fraction of the length)
    and a sine riser underneath."""

    def env(u):
        if u < peak:
            return (u / peak) ** 2.4
        return 1.0 - smooth((u - peak) / (1 - peak)) * 0.97

    w = noise_sweep(seconds, 150, 5000, env)
    mix_moving(w, t, gain, 0.35, 0.65, send=0.2)
    r = tone(lo, seconds, ((1.0, 1.0), (2.0, 0.2)), attack=seconds * peak * 0.9, tau=60.0, glide_to=hi, glide_s=seconds * peak)
    mix(r, t, gain * 0.5, 0.5, send=0.25)


SPK_POOL = [81, 84, 86, 88, 91, 93, 96, 98]  # A5 C6 D6 E6 G6 A6 C7 D7


def spark_wave(m, crushed):
    key = ("spark", m, crushed)
    if key not in _cache:
        w = tone(mtof(m), 0.16, ((1.0, 1.0), (2.0, 0.35), (3.0, 0.18)), attack=0.001, tau=0.035)
        _cache[key] = crush(w, 4, 4) if crushed else w
    return _cache[key]


def sparkle(t, n, step, gain, crushed=False, asc=True):
    """A glitter of quick high notes (A minor pentatonic), rising or falling."""
    for i in range(n):
        u = i / (n - 1)
        idx = round((u if asc else 1 - u) * (len(SPK_POOL) - 1)) + fx_rng.choice((-1, 0, 0, 1))
        m = SPK_POOL[min(max(idx, 0), len(SPK_POOL) - 1)]
        g = gain * ((0.6 + 0.4 * u) if asc else (1.0 - 0.5 * u))
        mix(spark_wave(m, crushed), t + i * step, g, fx_rng.uniform(0.15, 0.85), send=0.3)


def crackle(t, seconds, gain, d0, d1):
    """Bit-crushed noise ticks whose density goes from d0 to d1 (per 4 ms)."""
    k = 0
    while k * 0.004 < seconds:
        u = k * 0.004 / seconds
        if fx_rng.random() < d0 + (d1 - d0) * u:
            m = fx_rng.randint(24, 90)
            blip = zeros(m)
            v = 0.0
            for j in range(m):
                if j % 4 == 0:
                    v = round(fx_rng.uniform(-1, 1) * 3) / 3
                blip[j] = v * exp(-j / (m * 0.45))
            mix(blip, t + k * 0.004, gain * (1.0 - 0.6 * u), fx_rng.uniform(0.1, 0.9), send=0.1)
        k += 1


def wipe(t, asc):
    """Pixel dissolve: bit-crushed sparkle and crackle. Rising into the island,
    falling (softer) back into the room."""
    if asc:
        sparkle(t, 16, 0.032, 0.11, crushed=True, asc=True)
        crackle(t, 0.5, 0.1, 0.25, 0.6)
    else:
        sparkle(t, 14, 0.04, 0.1, crushed=True, asc=False)
        crackle(t, 0.6, 0.08, 0.5, 0.15)


def creak():
    """Wooden chest lid: a saw-like tone that slides up with a random wobble and
    a stick-slip amplitude flutter."""
    r = random.Random(77)
    m = int(0.75 * RATE)
    out = zeros(m)
    ph = jit = 0.0
    for n in range(m):
        u = n / m
        jit += 0.05 * (r.uniform(-1, 1) - jit)
        f = 140 + 120 * smooth(u) + 32 * jit
        ph += TAU * f / RATE
        v = sin(ph) + 0.6 * sin(2 * ph) + 0.45 * sin(3 * ph) + 0.3 * sin(4 * ph) + 0.2 * sin(5 * ph)
        am = 0.55 + 0.45 * sin(TAU * (17 + 10 * u) * n / RATE)
        env = smooth(u / 0.15) * (1 - smooth((u - 0.72) / 0.28))
        out[n] = v * am * env
    return fade_edges(peak_normalise(out), 44, 441)


def chest(t):
    """Chest opens: creak, a soft thunk as the lid stops, then a sparkle."""
    mix(creak(), t, 0.2, 0.45, send=0.15)
    mix(tone(mtof(43), 0.3, ((1.0, 1.0), (2.0, 0.4)), attack=0.003, tau=0.07), t + 0.7, 0.32, 0.5)
    sparkle(t + 0.75, 12, 0.055, 0.11, crushed=False, asc=True)


def dialog(t):
    """Soft UI pop: a small upward bloop and a quiet answering note."""
    w = tone(mtof(69), 0.3, ((1.0, 1.0), (2.0, 0.2)), attack=0.006, tau=0.08, glide_to=mtof(81), glide_s=0.05)
    mix(w, t, 0.22, 0.5, send=0.3)
    mix(tone(mtof(88), 0.3, attack=0.004, tau=0.07), t + 0.07, 0.07, 0.5, send=0.3)


def click(t):
    """Mouse click: a sharp tick with a tiny thump (down), then a softer release."""
    tk = hat_wave(92, 0.02, 0.003, 2500)
    th = tone(1200.0, 0.03, attack=0.001, tau=0.008)
    mix(tk, t, 0.42, 0.5)
    mix(th, t, 0.1, 0.5)
    mix(tk, t + 0.07, 0.24, 0.5)


def boing(t):
    """Happy little boing: the pitch springs upward, then a decaying wobble."""
    m = int(0.6 * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        tt = n / RATE
        f = 330 * (1 + 1.6 * (1 - exp(-tt / 0.06))) * (1 + 0.05 * sin(TAU * 15 * tt) * exp(-tt / 0.25))
        ph += TAU * f / RATE
        out[n] = (sin(ph) + 0.25 * sin(2 * ph)) * exp(-tt / 0.22) * min(1.0, n / 88)
    mix(fade_edges(out, 1, 441), t, 0.3, 0.5, send=0.2)
    mix(tone(mtof(93), 0.4, attack=0.002, tau=0.08), t + 0.1, 0.06, 0.55, send=0.3)


def build(t0, t1, count=32):
    """Logo blocks land: ticks that accelerate and climb an A minor pentatonic
    ladder, the last just before t1. Each is a short pitched blip and a wood tick."""
    ladder = [57, 60, 62, 64, 67, 69, 72, 74, 76, 79, 81, 84, 86, 88, 91, 93]
    wood = hat_wave(93, 0.03, 0.006, 1800)
    span = t1 - 0.25 - t0
    for k in range(count):
        x = k / (count - 1)
        t = t0 + span * (1 - (1 - x) ** 1.4)
        m = ladder[round(15 * x ** 0.9)]
        w = tone(mtof(m), 0.2, ((1.0, 1.0), (2.0, 0.3), (3.0, 0.1)), attack=0.001, tau=0.05)
        mix(w, t, 0.14 + 0.04 * x, 0.35 + 0.3 * ((k * 5) % 7) / 6, send=0.25)
        mix(wood, t, 0.08, 0.5)


# ---------------------------------------------------------------- score
render_pad()

# ---- open and problem: the room
cue_log = []  # (kind, t, sample) for every cue sound placed
dawn(cue_times("dawn")[0])
cue_log.append(("dawn", cue_times("dawn")[0]))
for t_, m_, p_ in ((1.6, 76, 0.35), (2.5, 81, 0.6), (3.3, 79, 0.45)):
    mix(pluck(m_, 1.8, 0.35), t_, 0.06, p_, send=0.4)

thinks = cue_times("think")
nopes = cue_times("nope")
for i, t_ in enumerate(thinks):
    think(t_, i)
for t_ in nopes:
    nope(t_)
cue_log += [("think", t_) for t_ in thinks] + [("nope", t_) for t_ in nopes]
room_skip = [(t_ - 0.05, t_ + 0.4) for t_ in thinks] + [(t_ - 0.05, t_ + 0.8) for t_ in nopes]
arp(S["problem"][0], S["problem"][1], 0.2, 64, 79, 0.055, skip=room_skip)

# ---- friend: phone, messages, dive into the screen
bz = cue_times("buzz")[0]
buzz(bz)
cue_log.append(("buzz", bz))
chats = cue_times("chat")
for t_ in chats:
    if CHAT_FROM.get(round(t_, 3)) == "me":
        msg_out(t_)
        cue_log.append(("chat(sent)", t_))
    else:
        msg_in(t_)
        cue_log.append(("chat(received)", t_))
whooshes = cue_times("whoosh")
dive = whooshes[0]
whoosh(dive, WIPES[0] - dive, 220.0, 1760.0, 0.92, 0.22)
cue_log.append(("whoosh(dive)", dive))
arp(S["friend"][0], dive, 0.22, 64, 81, 0.07,
    skip=[(bz - 0.05, bz + 0.9)] + [(t_ - 0.05, t_ + 0.6) for t_ in chats])
wipe(WIPES[0], True)
cue_log.append(("wipe", WIPES[0]))

# ---- the groove
KICK = kick_wave()
SNARE = snare_wave()
HAT_C = hat_wave(21, 0.05, 0.009, 7000)
HAT_O = hat_wave(22, 0.16, 0.045, 6000)
CRASH = hat_wave(23, 2.2, 0.55, 3500)
QUIET = [(56.4, 59.3)]  # QR + scan: the beat thins out
streams = cue_times("stream-start")
st_send, st_fold, st_toss = [t_ for t_ in streams if S["send"][0] <= t_ < S["send"][1]][0], \
    [t_ for t_ in streams if S["folders"][0] <= t_ < S["folders"][1]][0], \
    [t_ for t_ in streams if S["decide"][0] <= t_ < S["decide"][1]][0]
STREAMS = [(st_send, CHK[0]), (st_fold, CHK[1])]  # the arpeggio ducks under the streams

nbeats = int(round((GEND - G0) / BEAT))  # 75
for k in range(nbeats):
    tb = G0 + k * BEAT
    bar, bt = divmod(k, 4)
    light = in_any(QUIET, tb)
    lv = 0.8 if light else 1.0
    if bar >= 2 or bt in (0, 2):  # kick: halves first, then four on the floor
        mix(KICK, tb, (0.55 if k == 0 else 0.38 if bar >= 2 else 0.3) * lv, 0.5)
    if bar >= 1:  # shuffle hats on the first and last triplet of each beat
        hg = 0.085 * (0.55 if bar == 1 else 1.0) * lv
        mix(HAT_C, tb, hg * 0.6, 0.42)
        mix(HAT_O if k % 2 else HAT_C, tb + 2 * TRIP, hg, 0.6)
        if bar >= 4:
            mix(HAT_C, tb + TRIP, hg * 0.35, 0.5)
    if bar >= 4 and bt in (1, 3) and tb < 65.0:
        mix(SNARE, tb, 0.17 * lv, 0.5, send=0.15)
mix(CRASH, G0, 0.09, 0.5, send=0.2)
mix(pluck(57, 1.4, 0.45), G0, 0.09, 0.4, send=0.3)  # the groove lands: Am stab
mix(pluck(64, 1.4, 0.45), G0, 0.08, 0.5, send=0.3)
mix(pluck(69, 1.4, 0.45), G0, 0.07, 0.6, send=0.3)
mix(pluck(72, 1.4, 0.45), G0, 0.07, 0.55, send=0.3)
cue_log.append(("groove", G0))

# bass: triangle root with octave/fifth bounces, from the third bar
BASS_PAT = [(0, 0, 2), (2, 12, 1), (3, 0, 2), (5, 12, 1), (6, 0, 2), (8, 7, 1), (9, 0, 2), (11, 7, 1)]
for bar in range(2, NBARS):
    tb = G0 + bar * BAR
    for u, off, L in BASS_PAT:
        t_ = tb + u * TRIP
        if t_ >= GEND - 0.05:
            continue
        root = chord_at(t_ + 0.01)[0]
        w = tri_wave(root + off, L * TRIP * 0.95 + 0.03, tau=0.2)
        mix(w, t_, 0.14 * (1.0 if off == 0 else 0.7), 0.5)


# chip arpeggio on every triplet from bar 3 (a thin 12.5% pulse)
def arp_notes(ch):
    base = 57 + (ch[0] % 12 - 57) % 12
    return [base, base + (3 if ch in MINOR else 4), base + 7, base + 12]


def arp_lvl(t_):
    g = 0.5 if t_ < 31 else 0.7 if t_ < 46 else 0.8 if t_ < 55 else 0.65
    if in_any(STREAMS, t_):
        g *= 0.6
    if in_any(QUIET, t_):
        g *= 0.8
    return 0.08 * g


ARP_SEQ = (0, 1, 2, 3, 2, 1)
t_arp0 = G0 + 3 * BAR
for ku in range(int(round((GEND - t_arp0) / TRIP))):
    t_ = t_arp0 + ku * TRIP
    if t_ >= GEND - 0.1:
        break
    note = arp_notes(chord_at(t_ + 0.01))[ARP_SEQ[ku % 6]]
    mix(chip(note, 0.16, 0.125, tau=0.07), t_, arp_lvl(t_) * (1.2 if ku % 3 == 0 else 0.8), 0.35 if ku % 2 else 0.65, send=0.2)

# lead: A minor pentatonic, (triplet unit, midi, length in units); a pulse lead
# doubled by a pluck
MEL_A = [(0, 69, 2), (2, 72, 1), (3, 76, 3), (6, 74, 2), (8, 72, 1), (9, 74, 3),
         (12, 72, 2), (14, 69, 1), (15, 72, 3), (18, 74, 2), (20, 72, 1), (21, 69, 3),
         (24, 76, 2), (26, 79, 1), (27, 81, 3), (30, 79, 2), (32, 76, 1), (33, 74, 3),
         (36, 74, 2), (38, 76, 1), (39, 79, 3), (42, 76, 2), (44, 74, 1), (45, 76, 3)]
MEL_B = [(0, 76, 3), (3, 76, 2), (5, 74, 1), (6, 72, 3), (9, 74, 2), (11, 76, 1),
         (12, 72, 3), (15, 69, 2), (17, 72, 1), (18, 74, 3), (21, 72, 3),
         (24, 76, 3), (27, 79, 2), (29, 76, 1), (30, 81, 3), (33, 79, 3),
         (36, 81, 2), (38, 79, 1), (39, 76, 3), (42, 74, 2), (44, 76, 1), (45, 79, 3)]
hs = cue_times("handshake")[0]
lk = cue_times("lock")[0]
chest_t = cue_times("chest")[0]
MEL_DIPS = [(hs - 0.1, lk + 1.0, 0.4), (chest_t - 0.1, chest_t + 1.3, 0.4)]
PHRASES = [(G0 + 4 * BAR, MEL_A, 1.0), (G0 + 8 * BAR, MEL_B, 1.0),
           (G0 + 12 * BAR, MEL_A, 0.75), (G0 + 16 * BAR, MEL_B, 0.9)]
for p0, notes, pg in PHRASES:
    for u, m, L in notes:
        t_ = p0 + u * TRIP
        if t_ >= GEND - 0.3 or in_any(OVR, t_) or in_any(QUIET, t_):
            continue
        dur = L * TRIP * 0.92
        nxt = [a for a, _ in OVR if a > t_]
        if nxt:
            dur = min(dur, nxt[0] - t_)
        g = pg
        for a, b, f in MEL_DIPS:
            if a <= t_ < b:
                g *= f
        mix(chip(m, dur + 0.05, 0.25, tau=0.5, vib=0.006), t_, 0.085 * g, 0.5, send=0.3)
        mix(pluck(m, 0.9, 0.5), t_, 0.11 * g, 0.44, send=0.3)

# nearby: sonar pings; the third opens into a rising arpeggio
pings = cue_times("ping")
for i, p in enumerate(pings):
    ping(p, (76, 81, 81)[min(i, 2)], (0.28, 0.72, 0.5)[min(i, 2)])
    cue_log.append(("ping", p))
ping(pings[-1], 76, 0.5, gain=0.15)  # the third ping is a dyad ...
for j, m in enumerate((76, 81, 84, 88)):  # ... and the devices light up
    mix(pluck(m, 1.2, 0.5), pings[-1] + (j + 1) * TRIP, 0.09, 0.35 + 0.1 * j, send=0.35)
    mix(chip(m, 0.2, 0.25, tau=0.09), pings[-1] + (j + 1) * TRIP, 0.04, 0.35 + 0.1 * j, send=0.3)
for tb in (S["send"][0], S["folders"][0], S["phones"][0]):
    transition(tb)

# send: handshake, lock, stream, check
handshake(hs)
lock(lk)
stream(st_send, CHK[0] - 2 * TRIP)
cue_log += [("handshake", hs), ("lock", lk), ("stream-start", st_send)]

# folders: chest, cascade
chest(chest_t)
cascade(st_fold, CHK[1] - 3 * TRIP)
cue_log += [("chest", chest_t), ("stream-start", st_fold)]

# phones: QR blips, scan sweep, sealed packets past the relay
q = cue_times("qr")[0]
sc = cue_times("scan")[0]
rl = cue_times("relay")[0]
qr(q, sc - q)
scan(sc)
blobs(rl, CHK[2])
cue_log += [("qr", q), ("scan", sc), ("relay", rl)]

# the A-major checks inside the groove, and the ending of the beat
for i, c in enumerate(CHK):
    if c < GEND:
        chime(c, (0.65, 0.7, 0.5)[i], extra=(76,) if i else (), scale=1.7)
    cue_log.append(("check", c))
for i in range(10):  # snare roll into the wipe
    mix(SNARE, GEND - 1.0 + i * 0.1, (0.05 + 0.09 * i / 9), 0.5, send=0.15)
mix(KICK, GEND, 0.4, 0.5)
mix(CRASH, GEND, 0.1, 0.5, send=0.25)

# ---- back in the room
wipe(WIPES[-1], False)
cue_log.append(("wipe", WIPES[-1]))
mix(tone(mtof(45), 8.0, ((1.0, 1.0), (2.0, 0.3)), attack=0.3, tau=3.0), CALM, 0.13, 0.5)  # calm: low A
for j, m in enumerate((57, 64, 69, 72)):  # ... and a soft settling chord
    mix(pluck(m, 1.6, 0.35), CALM + 0.1 * j, 0.11, 0.35 + 0.1 * j, send=0.4)
cue_log.append(("calm", CALM))

dlg = cue_times("dialog")[0]
clk = cue_times("click")[0]
jmp = cue_times("jump")[0]
dialog(dlg)
click(clk)
toss(st_toss, 2.5)
boing(jmp)
chime(CHK[3], 0.5, extra=(76,), scale=1.3)
cue_log += [("dialog", dlg), ("click", clk), ("stream-start", st_toss), ("check", CHK[3]), ("jump", jmp)]
arp(CALM + 0.6, S["decide"][1], 0.22, 64, 81, 0.07,
    skip=[(dlg - 0.05, dlg + 0.5), (clk - 0.05, clk + 0.3), (st_toss - 0.1, CHK[3] - 0.4),
          (CHK[3] - 0.05, CHK[3] + 1.0), (chats[-1] - 0.05, chats[-1] + 0.8)])

# ---- outro: out of the window, the logo blocks assemble
fly = whooshes[1]
whoosh(fly, 2.4, 330.0, 1320.0, 0.55, 0.2)
cue_log.append(("whoosh(fly)", fly))
arp(S["outro"][0], fly - 0.1, 0.15, 64, 79, 0.06)
bd = cue_times("build")[0]
sw = cue_times("swell")[0]
build(bd, sw)
swell(sw, sw - bd - 0.4, 5.0, (57, 61, 64, 69, 76), 0.11)
cue_log += [("build", bd), ("swell", sw)]
arp(sw + 0.4, END_T - 1.0, 0.3, 69, 93, 0.07, t60=1.8)

# ---------------------------------------------------------------- final pass
pad_gain = curve([(0, 0.0), (cue_times("dawn")[0], 0.0), (4.0, 0.42), (13, 0.36), (18.0, 0.4), (WIPES[0], 0.7),
                  (G0, 0.8), (G0 + 1, 0.62), (GEND, 0.62), (GEND + 1.5, 0.33), (77, 0.36), (bd, 0.6),
                  (sw, 1.05), (END_T, 0.8)])
pad_cut = curve([(0, 600), (4, 900), (13, 1100), (18.4, 1800), (G0, 1600), (31, 2000), (46, 2300),
                 (55, 1900), (GEND, 1900), (GEND + 1.5, 1100), (77.5, 1200), (sw, 2600), (END_T, 1800)])
duck_depth = curve([(G0, 0.0), (G0 + 1, 0.28), (GEND - 0.2, 0.3), (GEND + 0.3, 0.0)])
FADE_S = DUR - END_T  # 2 s: from the end cue to silence at the last sample


def fade(t):
    if t >= DUR:
        return 0.0
    if t <= END_T:
        return 1.0
    return 0.5 * (1 + cos(math.pi * (t - END_T) / FADE_S))


DUCK = [min(1.0, j / 220) * exp(-j / (0.2 * RATE)) for j in range(BEAT_N)]
D = int(round(2 * TRIP * RATE))  # delay: two triplet 8ths = 0.4 s
FB, WET = 0.36, 0.55
a_damp = 1 - exp(-TAU * 2400 / RATE)
a_top = 1 - exp(-TAU * 11000 / RATE)
R_HP = exp(-TAU * 30 / RATE)
ringL, ringR = zeros(D), zeros(D)
outL, outR = zeros(N), zeros(N)
pl = pr = fl = fr = 0.0
xl1 = xr1 = hl = hr = ml = mr = 0.0
k = 0
for b0 in range(0, N, BLK):
    b1 = min(b0 + BLK, N)
    t = b0 / RATE
    ap = 1 - exp(-TAU * pad_cut(t) / RATE)
    pg = pad_gain(t)
    dd = duck_depth(t)
    fd0, fd1 = fade(t), fade(b1 / RATE)
    dfd = (fd1 - fd0) / (b1 - b0)
    fd = fd0
    j = b0 % BEAT_N
    for n in range(b0, b1):
        pl += ap * (padL[n] - pl)
        pr += ap * (padR[n] - pr)
        g = pg * (1 - dd * DUCK[j])
        j += 1
        if j == BEAT_N:
            j = 0
        wl = ringL[k]
        wr = ringR[k]
        fl += a_damp * (wl - fl)
        fr += a_damp * (wr - fr)
        ringL[k] = sendL[n] + FB * fr  # ping-pong: each side feeds the other
        ringR[k] = sendR[n] + FB * fl
        k += 1
        if k == D:
            k = 0
        xl = pl * g + dryL[n] + WET * wl
        xr = pr * g + dryR[n] + WET * wr
        hl = R_HP * (hl + xl - xl1)
        hr = R_HP * (hr + xr - xr1)
        xl1, xr1 = xl, xr
        ml += a_top * (hl - ml)
        mr += a_top * (hr - mr)
        outL[n] = ml * fd
        outR[n] = mr * fd
        fd += dfd
outL[N - 1] = outR[N - 1] = 0.0  # silent on the very last sample

# Soft-clip (tanh), then normalise to -1.5 dBFS peak and write 16-bit stereo.
# WHY: kick, stabs and chimes pile up into rare peaks ~14 dB over the average;
# a gentle tanh (linear for small signals) trims them so the beat sits louder
# while the peak still lands exactly on -1.5 dBFS.
DRIVE = 1.25
peak = max(max(outL), -min(outL), max(outR), -min(outR)) or 1.0
knee = math.tanh(DRIVE)
outL = [math.tanh(DRIVE * x / peak) / knee for x in outL]
outR = [math.tanh(DRIVE * x / peak) / knee for x in outR]
scale = 10 ** (-1.5 / 20) * 32767
pcm = array.array("h", bytes(4 * N))
pcm[0::2] = array.array("h", [round(x * scale) for x in outL])
pcm[1::2] = array.array("h", [round(x * scale) for x in outR])
if sys.byteorder == "big":
    pcm.byteswap()
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "web", "film", "film.wav")
with wave.open(out, "wb") as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(RATE)
    w.writeframes(pcm.tobytes())
print(f"wrote {out}: {N / RATE:.3f}s, {RATE} Hz 16-bit stereo, {time.time() - T_START:.1f}s to render")
for c in TL["cues"]:
    print(f"  cue {c['kind']:<12} {c['t']:6.2f}s -> sample {at(c['t'])}")
