#!/usr/bin/env python3
"""Algorithmic soundtrack + sound effects for the 90 s launch reel (web/reel/).

Pure code, standard library only, fixed seeds: the same WAV byte for byte on
every run. No samples, nothing generated by a model. Bpm, scenes, cues and
stickerTimes are read from web/reel/timeline.json and every cue sound is
scheduled on the exact sample of its cue time.

    python3 scripts/reel_music.py web/reel/film.wav

Feel: 90 bpm (beat 0.6667 s, bar 2.6667 s), A minor (Am - F - C - G, one chord
per bar) with a bright A major lift at the check and at the final chord. Modern
keynote-reel energy: sine/saw sub bass, sidechain-pumped pad, plucked 16th
arps, a saw lead hook, 4-on-the-floor with claps and shuffled hats.

Sections (bars of 2.6667 s, all aligned to t = 0):
  0-2       digital silence
  2-8       wind swirl (music) + low A drone + ticking texture from 5.333
  8.0       impact, then a light beat (kick on 1 and 3, soft hats) to 21.33;
            the bass enters at 16
  21.33-37.33 build: 4-on-the-floor, claps on 2 and 4, bass line, 16th arps,
            the pad filter opens; snare rolls under the risers (25.33, 36)
  37.33-58.67 DROP: heavy sub bass, pumping pad, lead hook, full beat
  58.67-66.67 breather: no drums, soft pad, gentle keys, air; riser 65.33
  66.67-85.33 DROP 2: brighter, octave lead, extra percussion 74.67-80
  85.33-90  collapse, final A major chord at 87.333, fade 88.5 -> 90.0

Signal path: sources go to buses (pad stereo, bass mono, dry stereo, delay
send mono). One final pass: pad low-pass + sidechain duck, bass duck, dotted-8th
ping-pong delay, 28 Hz high-pass, 12 kHz top, master fade; then a look-ahead
peak limiter, a gentle tanh, and a normalise to -1.5 dBFS.
"""

import array
import json
import math
import os
import random
import sys
import time
import wave

T_START = time.time()
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(ROOT, "web", "reel", "timeline.json"), encoding="utf-8") as fh:
    TL = json.load(fh)

RATE = 44100
DUR = float(TL["duration"])
N = int(round(DUR * RATE))
BEAT = 60.0 / float(TL["bpm"])  # 0.6667 s
BAR = 4 * BEAT  # 2.6667 s
S16 = BEAT / 4  # 0.16667 s
BEAT_N = int(round(BEAT * RATE))  # 29400
TAU = 2 * math.pi
sin, cos, exp = math.sin, math.cos, math.exp
Rnd = random.Random

END_T = [float(c["t"]) for c in TL["cues"] if c["kind"] == "end"][0]  # 88.5
CHECK_T = [float(c["t"]) for c in TL["cues"] if c["kind"] == "check"][0]  # 52.0
CHORD_T = [float(c["t"]) for c in TL["cues"] if c["kind"] == "chord"][0]  # 87.333
DROP1 = [float(s["start"]) for s in TL["scenes"] if s["id"] == "sealed"][0]  # 37.333
BREATHER = [float(s["start"]) for s in TL["scenes"] if s["id"] == "breather"][0]  # 58.667
DROP2 = [float(s["start"]) for s in TL["scenes"] if s["id"] == "phones"][0]  # 66.667
OUTRO = [float(s["start"]) for s in TL["scenes"] if s["id"] == "outro"][0]  # 85.333


def at(t):
    return int(round(t * RATE))


def zeros(m):
    return array.array("d", bytes(8 * m))


def mtof(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def smooth(u):
    u = min(max(u, 0.0), 1.0)
    return u * u * (3 - 2 * u)


def pan_gains(p):
    p = min(max(p, 0.0), 1.0)
    return cos(p * math.pi / 2), sin(p * math.pi / 2)


def curve(points):
    def f(t):
        if t <= points[0][0]:
            return points[0][1]
        for (t0, v0), (t1, v1) in zip(points, points[1:]):
            if t <= t1:
                return v0 + (v1 - v0) * (t - t0) / (t1 - t0)
        return points[-1][1]

    return f


# ---------------------------------------------------------------- buses
padL, padR = zeros(N), zeros(N)
bassM = zeros(N)
dryL, dryR = zeros(N), zeros(N)
sendM = zeros(N)


def addto(buf, s, wav, g):
    if s < 0:
        wav = wav[-s:]
        s = 0
    m = min(len(wav), N - s)
    if m <= 0:
        return
    seg = buf[s:s + m]
    buf[s:s + m] = array.array("d", [a + b * g for a, b in zip(seg, wav)])


def mix(wav, t, gain, pan=0.5, send=0.0):
    """Add a mono waveform at time t (on the exact sample), fixed pan, optional delay send."""
    s = at(t)
    gl, gr = pan_gains(pan)
    addto(dryL, s, wav, gain * gl)
    addto(dryR, s, wav, gain * gr)
    if send:
        addto(sendM, s, wav, gain * send)


def mix_at(wav, s, gain, pan=0.5, send=0.0):
    """Same as mix() but with an explicit start sample."""
    gl, gr = pan_gains(pan)
    addto(dryL, s, wav, gain * gl)
    addto(dryR, s, wav, gain * gr)
    if send:
        addto(sendM, s, wav, gain * send)


def mix_moving(wav, t, gain, p0=0.5, p1=0.5, send=0.0, pf=None, s=None):
    """Mix with a pan that moves (linear p0 -> p1, or pf(u)); updated every 128 samples."""
    s = at(t) if s is None else s
    L = len(wav)
    B = 128
    for b0 in range(0, L, B):
        u = min(1.0, (b0 + B / 2) / L)
        p = pf(u) if pf else p0 + (p1 - p0) * u
        gl, gr = pan_gains(p)
        seg = wav[b0:b0 + B]
        addto(dryL, s + b0, seg, gain * gl)
        addto(dryR, s + b0, seg, gain * gr)
        if send:
            addto(sendM, s + b0, seg, gain * send)


def mix_bass(wav, t, gain):
    addto(bassM, at(t), wav, gain)


def fade_edges(w, attack_n=44, release_n=441):
    m = len(w)
    for j in range(min(attack_n, m)):
        w[j] *= j / attack_n
    for j in range(min(release_n, m)):
        w[m - 1 - j] *= j / release_n
    return w


def norm(w, peak=1.0):
    pk = max(max(w), -min(w)) or 1.0
    k = peak / pk
    return array.array("d", [x * k for x in w])


# ---------------------------------------------------------------- voices
_cache = {}


def pluck(midi, t60=1.2, bright=0.5):
    """Karplus-Strong string with an all-pass tuning filter."""
    key = ("pluck", midi, t60, bright)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    r = Rnd(1000 + midi * 7 + int(bright * 100))
    total = RATE / f - 0.5
    P = int(total)
    frac = total - P
    if frac < 0.1:
        P -= 1
        frac += 1
    C = (1 - frac) / (1 + frac)
    loss = 10 ** (-3 / (t60 * f))
    noise = [r.uniform(-1, 1) for _ in range(P)]
    line = [0.0] * P
    s1 = 0.0
    for i in range(2 * P):
        s1 += bright * (noise[i % P] - s1)
        line[i % P] = s1
    mean = sum(line) / P
    peak = max(abs(x - mean) for x in line) or 1.0
    line = [(x - mean) / peak for x in line]
    m = int(min(3.0, t60 * 1.05) * RATE)
    out = zeros(m)
    prev = x1 = y1 = 0.0
    k = 0
    for n in range(m):
        s = line[k]
        out[n] = s
        avg = loss * 0.5 * (s + prev)
        prev = s
        y1 = C * avg + x1 - C * y1
        x1 = avg
        line[k] = y1
        k += 1
        if k == P:
            k = 0
    _cache[key] = fade_edges(out, 22, 1323)
    return _cache[key]


def tone(freq, seconds, partials=((1.0, 1.0),), attack=0.005, tau=0.5, glide_to=None, glide_s=0.0):
    """Additive sine tone with exponential decay and optional log-frequency glide."""
    key = ("tone", freq, seconds, partials, attack, tau, glide_to, glide_s)
    if key in _cache:
        return _cache[key]
    m = int(seconds * RATE)
    out = zeros(m)
    ph = 0.0
    inc = TAU * freq / RATE
    ea = 1.0 / max(1, attack * RATE)
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0
    gn = max(1, int(glide_s * RATE))
    ratio = (glide_to / freq) if glide_to else 1.0
    for n in range(m):
        if glide_to and n <= gn:
            inc = TAU * freq * ratio ** smooth(n / gn) / RATE
        v = 0.0
        for r, a in partials:
            v += a * sin(r * ph)
        ph += inc
        out[n] = v * min(1.0, n * ea) * dec
        dec *= ed
    _cache[key] = fade_edges(out, 1, 441)
    return _cache[key]


BELL_PARTS = ((1.0, 1.0, 1.0), (2.76, 0.42, 0.55), (5.4, 0.22, 0.32), (8.93, 0.1, 0.18))
GLASS_PARTS = ((1.0, 1.0, 1.0), (2.32, 0.6, 0.6), (4.25, 0.4, 0.4), (6.63, 0.25, 0.3), (9.38, 0.15, 0.2))


def bell(freq, seconds, tau, parts=BELL_PARTS):
    """Glassy bell: inharmonic partials, the upper ones dying faster."""
    key = ("bell", round(freq, 3), seconds, tau, parts)
    if key in _cache:
        return _cache[key]
    m = int(seconds * RATE)
    out = zeros(m)
    for r, a, dm in parts:
        if freq * r > 18000:
            continue
        inc = TAU * freq * r / RATE
        ed = exp(-1.0 / (tau * dm * RATE))
        d = a
        ph = 0.0
        for n in range(m):
            out[n] += sin(ph) * d
            ph += inc
            d *= ed
    for n in range(min(88, m)):
        out[n] *= n / 88
    _cache[key] = fade_edges(norm(out), 1, 441)
    return _cache[key]


def noise_sweep(seconds, fmin, fmax, cut_fn, amp_fn=None, rg=None, hp=0.0):
    """Filtered-noise whoosh: white noise through two one-pole low-passes whose
    cutoff follows cut_fn(u) in 0..1; amp_fn(u) is the loudness; optional high-pass."""
    rg = rg or Rnd(1)
    rnd = rg.random
    m = int(seconds * RATE)
    out = zeros(m)
    s1 = s2 = s3 = 0.0
    ahp = 1 - exp(-TAU * hp / RATE) if hp else 0.0
    B = 16
    c0 = cut_fn(0.0)
    e0 = amp_fn(0.0) if amp_fn else c0
    for b0 in range(0, m, B):
        b1 = min(b0 + B, m)
        c1 = cut_fn(b1 / m)
        e1 = amp_fn(b1 / m) if amp_fn else c1
        a = 1 - exp(-TAU * (fmin + (fmax - fmin) * c0) / RATE)
        de = (e1 - e0) / (b1 - b0)
        e = e0
        for n in range(b0, b1):
            x = rnd() * 2 - 1
            s1 += a * (x - s1)
            s2 += a * (s1 - s2)
            y = s2
            if ahp:
                s3 += ahp * (y - s3)
                y -= s3
            out[n] = y * e
            e += de
        c0, e0 = c1, e1
    return fade_edges(norm(out), 44, 441)


def hat_wave(seed, seconds, tau, hp=6000):
    r = Rnd(seed)
    m = int(seconds * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * hp / RATE)
    lp = 0.0
    for n in range(m):
        x = r.random() * 2 - 1
        lp += a * (x - lp)
        out[n] = (x - lp) * exp(-n / (tau * RATE))
    return fade_edges(norm(out), 22, 220)


def kick_wave(f_lo=48.0, f_hi=165.0, dec=0.15, drive=2.0, length=0.5):
    m = int(length * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        t = n / RATE
        ph += TAU * (f_lo + (f_hi - f_lo) * exp(-t / 0.02)) / RATE
        v = sin(ph) * exp(-t / dec)
        if n < 130:
            v += 0.45 * sin(TAU * 3100 * t) * exp(-t / 0.0015)
        out[n] = math.tanh(drive * v)
    return fade_edges(norm(out), 1, 441)


def sub_wave(f0, f1, seconds, tau, tc=0.3):
    """Sub boom: a sine falling f0 -> f1, long decay."""
    m = int(seconds * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        t = n / RATE
        ph += TAU * (f1 + (f0 - f1) * exp(-t / tc)) / RATE
        out[n] = (sin(ph) + 0.18 * sin(2 * ph)) * exp(-t / tau) * min(1.0, n / 110)
    return fade_edges(norm(out), 1, 882)


def clap_wave():
    r = Rnd(51)
    m = int(0.4 * RATE)
    out = zeros(m)
    a1 = 1 - exp(-TAU * 1000 / RATE)
    a2 = 1 - exp(-TAU * 6500 / RATE)
    lp1 = lp2 = 0.0
    bursts = (0.0, 0.011, 0.023, 0.036)
    for n in range(m):
        t = n / RATE
        x = r.random() * 2 - 1
        lp1 += a1 * (x - lp1)
        lp2 += a2 * ((x - lp1) - lp2)
        e = 0.0
        for h in bursts:
            if t >= h:
                e += exp(-(t - h) / 0.0045)
        e += 0.7 * exp(-max(0.0, t - 0.036) / 0.07) * (t >= 0.036)
        out[n] = lp2 * e
    return fade_edges(norm(out), 22, 441)


def snare_wave(seed=41, length=0.3, tau=0.065, body=185):
    r = Rnd(seed)
    m = int(length * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * 1800 / RATE)
    lp = ph = 0.0
    for n in range(m):
        t = n / RATE
        x = r.random() * 2 - 1
        lp += a * (x - lp)
        ph += TAU * (body + 120 * exp(-t / 0.02)) / RATE
        out[n] = (x - lp) * 0.75 * exp(-t / tau) + sin(ph) * 0.6 * exp(-t / 0.05)
    return fade_edges(norm(out), 22, 441)


def shaker_wave():
    r = Rnd(61)
    m = int(0.09 * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * 5000 / RATE)
    lp = 0.0
    for n in range(m):
        x = r.random() * 2 - 1
        lp += a * (x - lp)
        t = n / RATE
        out[n] = (x - lp) * min(1.0, t / 0.012) * exp(-t / 0.028)
    return fade_edges(norm(out), 22, 220)


def tom_wave(f0):
    m = int(0.35 * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        t = n / RATE
        ph += TAU * f0 * (1 + 0.7 * exp(-t / 0.03)) / RATE
        out[n] = (sin(ph) + (0.4 * sin(TAU * 3000 * t) * exp(-t / 0.002))) * exp(-t / 0.11)
    return fade_edges(norm(out), 1, 441)


SAW_SIZE = 2048


def saw_table(f):
    key = ("saw", round(f, 2))
    if key in _cache:
        return _cache[key]
    H = max(1, min(48, int(9000 / f)))
    tab = [0.0] * SAW_SIZE
    for h in range(1, H + 1):
        w = TAU * h / SAW_SIZE
        for i in range(SAW_SIZE):
            tab[i] += sin(w * i) / h
    pk = max(abs(v) for v in tab)
    tab = [v / pk for v in tab]
    _cache[key] = tab
    return tab


def bass_wave(midi, steps, level):
    """Sub sine + low-passed saw; level 0 (soft) .. 2 (heavy)."""
    key = ("bass", midi, steps, level)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    tab = saw_table(f)
    secs = steps * S16 * 0.97 + 0.03
    m = int(secs * RATE)
    out = zeros(m)
    a = 1 - exp(-TAU * (180 + 520 * level + 3 * f) / RATE)
    lp = 0.0
    ph = 0.0
    inc = f / RATE * SAW_SIZE
    sp = 0.0
    sinc = TAU * f / RATE
    mixv = (0.0, 0.35, 0.6)[level]
    ed = exp(-1.0 / (0.5 * RATE))
    dec = 1.0
    for n in range(m):
        lp += a * (tab[int(ph) & (SAW_SIZE - 1)] - lp)
        ph += inc
        v = sin(sp) + mixv * lp * 1.6
        sp += sinc
        out[n] = v * dec * min(1.0, n / 180)
        dec *= ed
    if level == 2:
        out = array.array("d", [math.tanh(1.4 * x) for x in out])
    _cache[key] = fade_edges(norm(out), 1, 500)
    return _cache[key]


def lead_wave(midi, secs, sus=0.55, tau=0.25, lp_hz=3800):
    """Detuned saw pair, soft attack, exponential fall to a sustain."""
    key = ("lead", midi, round(secs, 3), sus, tau, lp_hz)
    if key in _cache:
        return _cache[key]
    f = mtof(midi)
    tab = saw_table(f)
    m = int(secs * RATE)
    out = zeros(m)
    i1 = f / RATE * SAW_SIZE
    i2 = i1 * 1.0046
    i3 = i1 * 0.9954
    p1, p2, p3 = 0.0, 611.0, 1303.0
    a = 1 - exp(-TAU * lp_hz / RATE)
    lp = 0.0
    ed = exp(-1.0 / (tau * RATE))
    dec = 1.0 - sus
    mask = SAW_SIZE - 1
    for n in range(m):
        v = tab[int(p1) & mask] + tab[int(p2) & mask] + tab[int(p3) & mask]
        p1 += i1
        p2 += i2
        p3 += i3
        lp += a * (v - lp)
        out[n] = lp * (sus + dec) * min(1.0, n / 260)
        dec *= ed
    _cache[key] = fade_edges(norm(out), 1, 700)
    return _cache[key]


def crush(w, hold=4, bits=4):
    lv = 2 ** (bits - 1)
    out = zeros(len(w))
    v = 0.0
    for j in range(len(w)):
        if j % hold == 0:
            v = round(w[j] * lv) / lv
        out[j] = v
    return fade_edges(out, 1, 220)


def rise_tone(d, f0, f1, pw=1.8, partials=((1.0, 1.0), (2.0, 0.3), (3.0, 0.12))):
    """Exponential pitch riser whose loudness grows as u**pw."""
    key = ("rise", d, f0, f1, pw, partials)
    if key in _cache:
        return _cache[key]
    m = int(d * RATE)
    out = zeros(m)
    ph = 0.0
    r = f1 / f0
    for n in range(m):
        u = n / m
        ph += TAU * f0 * r ** u / RATE
        v = 0.0
        for q, a in partials:
            v += a * sin(q * ph)
        out[n] = v * u ** pw
    _cache[key] = fade_edges(out, 44, 220)
    return _cache[key]


def tick_wave(seed, secs=0.02, tau=0.003, hp=2500):
    return hat_wave(seed, secs, tau, hp)


# ---------------------------------------------------------------- harmony
# name: (bass midi, pad voicing, arp pool of 6 tones, minor?)
CH = {
    "Am": (33, (57, 60, 64, 69), (57, 60, 64, 69, 72, 76)),
    "F": (29, (53, 60, 65, 69), (57, 60, 65, 69, 72, 77)),
    "C": (36, (55, 60, 64, 67), (55, 60, 64, 67, 72, 76)),
    "G": (31, (55, 59, 62, 67), (55, 59, 62, 67, 71, 74)),
    "A": (33, (57, 61, 64, 69, 73), (57, 61, 64, 69, 73, 76)),  # A major lift
}
BAR_CH = {}
for _b, _c in enumerate(
    ["Am", "Am", "Am", "Am", "F", "C", "G", "F",  # 0-7
     "Am", "F", "C", "G", "F", "G",  # 8-13 build
     "Am", "F", "C", "G", "Am", "F", "C", "G",  # 14-21 drop
     "Am", "F", "C",  # 22-24 breather
     "Am", "F", "C", "G", "Am", "F", "G",  # 25-31 drop 2
     "G"]):  # 32 outro
    BAR_CH[_b] = _c
OVERRIDES = [(CHECK_T - 0.1, 53.3333, "A"), (CHORD_T, DUR + 1.0, "A")]


def chord_name(t):
    for a, b, c in OVERRIDES:
        if a <= t < b:
            return c
    return BAR_CH.get(int(t / BAR + 1e-9), "G")


def chord(t):
    return CH[chord_name(t + 1e-6)]


# ---------------------------------------------------------------- pad
PAD_SIZE = 4096
PAD_TAB = [sum(sin(h * TAU * i / PAD_SIZE) / h ** 1.7 for h in range(1, 8)) for i in range(PAD_SIZE)]
_pk = max(abs(v) for v in PAD_TAB)
PAD_TAB = [v / _pk for v in PAD_TAB]
pad_rng = Rnd(5)
BLK = 256


def render_pad():
    bounds = {0.0, DUR}
    for b in range(0, 34):
        bounds.add(b * BAR)
    for a, b, _ in OVERRIDES:
        bounds.add(a)
        bounds.add(min(b, DUR))
    pts = sorted(x for x in bounds if 2.0 - BAR <= x <= DUR)
    segs = []
    for i, t0 in enumerate(pts[:-1]):
        name = chord_name((t0 + pts[i + 1]) / 2)
        if segs and segs[-1][2] == name:
            segs[-1][1] = pts[i + 1]
        else:
            segs.append([t0, pts[i + 1], name])
    XF = 0.35
    for si, (t0, t1, name) in enumerate(segs):
        first, last = si == 0, si == len(segs) - 1
        a = max(2.0, t0 - (0 if first else XF / 2))
        b = t1 if last else t1 + XF / 2
        n0, n1 = at(a), min(N, at(b))
        if n1 <= n0:
            continue
        notes = CH[name][1]

        def env(t, t0=t0, t1=t1, first=first, last=last):
            e = 1.0
            if not first:
                e *= sin(math.pi / 2 * min(max((t - t0 + XF / 2) / XF, 0.0), 1.0))
            if not last:
                e *= cos(math.pi / 2 * min(max((t - t1 + XF / 2) / XF, 0.0), 1.0))
            return e

        for v, midi in enumerate(notes):
            f = mtof(midi)
            for side, det in enumerate((-0.0028, 0.0028)):
                inc = f * (1 + det) / RATE * PAD_SIZE
                ph = pad_rng.uniform(0, PAD_SIZE)
                gA, gB = (0.8, 0.3) if side == 0 else (0.3, 0.8)
                vol = 0.06 * (0.75 if midi > 70 else 1.0)
                rate = 0.06 + 0.021 * v
                lph = pad_rng.uniform(0, TAU)
                L, R = padL, padR
                g0 = vol * env(n0 / RATE) * (1 + 0.2 * sin(lph + TAU * rate * n0 / RATE))
                for b0 in range(n0, n1, BLK):
                    b1 = min(b0 + BLK, n1)
                    tt = b1 / RATE
                    g1 = vol * env(tt) * (1 + 0.2 * sin(lph + TAU * rate * tt))
                    dg = (g1 - g0) / (b1 - b0)
                    g = g0
                    for n in range(b0, b1):
                        s = PAD_TAB[int(ph) & 4095] * g
                        ph += inc
                        g += dg
                        L[n] += s * gA
                        R[n] += s * gB
                    g0 = g1


# ---------------------------------------------------------------- music
KICK = kick_wave()
KICK_SOFT = kick_wave(f_lo=52, f_hi=120, dec=0.13, drive=1.4)
CLAP = clap_wave()
SNARE = snare_wave()
HAT_C = hat_wave(21, 0.05, 0.009, 7000)
HAT_O = hat_wave(22, 0.2, 0.06, 6500)
CRASH = hat_wave(23, 3.0, 0.7, 3500)
SHAKER = shaker_wave()
WOOD = tone(1500.0, 0.05, ((1.0, 1.0), (2.4, 0.6)), attack=0.0006, tau=0.011)
CLAVE = tone(2300.0, 0.08, ((1.0, 1.0), (2.1, 0.4)), attack=0.0005, tau=0.02)
TOMS = {"lo": tom_wave(130.0), "mid": tom_wave(170.0), "hi": tom_wave(225.0)}

mus_rng = Rnd(90)


def bar_of(t):
    return int(t / BAR + 1e-9)


def section(t):
    b = bar_of(t)
    if 3 <= b <= 7:
        return "intro"
    if 8 <= b <= 13:
        return "build"
    if 14 <= b <= 21 or 25 <= b <= 31:
        return "drop"
    return None


ROLLS = [(25.3333, 26.6667, 0.05, 0.13), (36.0, 37.3333, 0.07, 0.2), (65.3333, 66.6667, 0.05, 0.13)]


def drums():
    sw = 0.09 * S16  # light shuffle on the odd 16ths
    for g in range(0, int(round(DUR / S16))):
        t = g * S16
        sec = section(t)
        if sec is None:
            continue
        if 36.0 <= t < DROP1:  # pre-drop: drums out, the roll takes over
            continue
        st = g % 16
        bar = g // 16
        bt, sub = divmod(st, 4)
        fl = 0.0 if sub else 1.0  # on a beat
        if sec == "intro":
            if st in (0, 8):
                mix(KICK_SOFT, t, 0.42 if g != 48 else 0.6, 0.5)
            if st in (2, 6, 10, 14):
                mix(HAT_C, t, 0.045, 0.6)
            if st in (4, 12) and bar >= 5:
                mix(SHAKER, t, 0.05, 0.4)
            continue
        if sec == "build":
            ramp = 0.75 + 0.25 * min(1.0, (bar - 8) / 5)
            if st in (0, 4, 8, 12) and bar >= 9:
                mix(KICK, t, 0.5 * ramp, 0.5)
            elif st in (0, 8) and bar == 8:
                mix(KICK_SOFT, t, 0.45, 0.5)
            if st in (4, 12):
                mix(CLAP, t, 0.17 * ramp, 0.52, send=0.2)
                mix(SNARE, t, 0.06 * ramp, 0.5)
            if st % 2 == 0:
                if st in (2, 6, 10, 14) and bar >= 10:
                    mix(HAT_O, t, 0.05, 0.62)
                else:
                    mix(HAT_C, t, 0.048 * (1.0 if st % 4 == 0 else 0.7), 0.4)
            elif bar >= 12:
                mix(HAT_C, t + sw, 0.025, 0.55)
            if st % 4 == 2:
                mix(SHAKER, t, 0.035, 0.35 + 0.3 * ((g // 4) % 2))
            continue
        # drop
        second = bar >= 25
        if st in (0, 4, 8, 12):
            mix(KICK, t, 0.62, 0.5)
        if second and st == 10 and bar >= 27:
            mix(KICK, t, 0.28, 0.5)
        if st in (4, 12):
            mix(CLAP, t, 0.24, 0.52, send=0.25)
            mix(SNARE, t, 0.09, 0.5, send=0.1)
        if st in (2, 6, 10, 14):
            mix(HAT_O, t, 0.06, 0.64)
        else:
            mix(HAT_C, t + (sw if st % 2 else 0.0), (0.05, 0.022, 0.034, 0.022)[st % 4] * (1.15 if second else 1.0), 0.4 + 0.2 * (st % 2))
        mix(SHAKER, t + (sw if st % 2 else 0.0), 0.028 if st % 2 else 0.02, 0.3 + 0.4 * (st % 2))
        # extra percussion under the stickers
        if 74.6 <= t < 80.0:
            if st in (3, 7, 11, 13, 15):
                nm = ("lo", "mid", "hi", "mid", "hi")[(3, 7, 11, 13, 15).index(st)]
                mix(TOMS[nm], t, 0.28, 0.3 + 0.4 * ((st % 3) / 2), send=0.2)
            if st in (1, 5, 9, 14):
                mix(CLAVE, t, 0.12, 0.7 if st in (1, 9) else 0.3, send=0.2)
            if st in (2, 10):
                mix(SHAKER, t, 0.05, 0.5)


def snare_rolls():
    for a, b, g0, g1 in ROLLS:
        t = a
        d = b - a
        while t < b - 0.01:
            u = (t - a) / d
            mix(SNARE, t, g0 + (g1 - g0) * u, 0.5, send=0.12)
            t += max(0.03, S16 * (1.0 - 0.8 * u ** 1.3))


P_INTRO = [(0, 0, 6), (8, 0, 4), (12, 7, 4)]
P_BUILD = [(0, 0, 3), (4, 0, 1), (6, 0, 2), (8, 0, 3), (12, 7, 2), (14, 12, 2)]
P_DROP = [(0, 0, 3), (3, 0, 1), (4, 12, 1), (6, 0, 2), (8, 0, 3), (11, 12, 1), (12, 7, 2), (14, 0, 2)]


def bass_line():
    for bar in range(6, 32):
        if BREATHER <= bar * BAR < DROP2:
            continue
        sec = section(bar * BAR)
        if sec is None:
            continue
        pat, lv, gain = (P_INTRO, 0, 0.34) if sec == "intro" else (P_BUILD, 1, 0.42) if sec == "build" else (P_DROP, 2, 0.5)
        if sec == "build":
            lv = 1 if bar < 12 else 2
        for st, off, L in pat:
            t = bar * BAR + st * S16
            if 36.0 <= t < DROP1 or t >= OUTRO:
                continue
            root = chord(t + 0.01)[0]
            if root < 33 and off == 0 and sec == "drop":
                root += 0  # F1 (29) keeps the sub; the saw layer carries the pitch
            mix_bass(bass_wave(root + off, L, lv), t, gain * (1.0 if off == 0 else 0.7))


ARP_SEQ = (0, 1, 2, 3, 2, 1, 2, 3, 4, 3, 2, 3, 4, 5, 4, 3)


def arps():
    r = Rnd(77)
    for g in range(int(round(DUR / S16))):
        t = g * S16
        b = bar_of(t)
        sec = section(t)
        if sec not in ("build", "drop") or 36.0 <= t < DROP1:
            continue
        st = g % 16
        pool = chord(t + 0.01)[2]
        idx = ARP_SEQ[st]
        midi = pool[idx] + (12 if idx < 2 else 0)
        if sec == "build":
            gain = 0.045 + 0.055 * min(1.0, (t - 21.33) / 14.0)
        elif b >= 25:
            gain = 0.085
            midi += 12 if st % 8 in (5, 6) else 0
        else:
            gain = 0.07
        accent = 1.0 if st % 4 == 0 else 0.75 if st % 2 == 0 else 0.55
        mix(pluck(midi, 0.32, 0.55), t, gain * accent * r.uniform(0.9, 1.0), 0.3 + 0.4 * (st % 2) + 0.06 * (st // 8), send=0.42 if st % 2 == 0 else 0.15)


# lead hook: (step in 16ths from phrase start, midi, length in 16ths)
HOOK_A = [(0, 76, 3), (3, 76, 1), (4, 79, 3), (7, 76, 1), (8, 74, 2), (10, 72, 2), (12, 69, 4),
          (16, 72, 3), (19, 72, 1), (20, 76, 3), (23, 74, 1), (24, 72, 2), (26, 69, 2), (28, 72, 4),
          (32, 79, 3), (35, 79, 1), (36, 84, 3), (39, 79, 1), (40, 76, 2), (42, 79, 2), (44, 76, 4),
          (48, 74, 3), (51, 76, 1), (52, 74, 2), (54, 72, 2), (56, 74, 4), (60, 76, 2), (62, 79, 2)]
HOOK_B = [(0, 81, 3), (3, 81, 1), (4, 84, 3), (7, 81, 1), (8, 79, 2), (10, 76, 2), (12, 76, 4),
          (16, 77, 3), (19, 76, 1), (20, 81, 3), (23, 79, 1), (24, 76, 2), (26, 72, 2), (28, 76, 4),
          (32, 79, 2), (34, 84, 2), (36, 88, 3), (39, 86, 1), (40, 84, 2), (42, 79, 2), (44, 84, 4),
          (48, 79, 3), (51, 79, 1), (52, 76, 2), (54, 74, 2), (56, 79, 4), (60, 81, 2), (62, 86, 2)]


def lead_phrase(t0, notes, bars_limit, gain, octave_double=False, harmony=False):
    for st, m, L in notes:
        if st >= bars_limit * 16:
            continue
        t = t0 + st * S16
        dur = L * S16 * 0.93
        mix(lead_wave(m, dur + 0.06, sus=0.55, tau=0.22), t, gain, 0.5, send=0.3)
        mix(pluck(m, 0.6, 0.5), t, gain * 0.55, 0.42, send=0.3)
        if octave_double:
            mix(lead_wave(m + 12, dur + 0.04, sus=0.4, tau=0.15, lp_hz=5500), t, gain * 0.38, 0.62, send=0.35)
        if harmony:
            mix(lead_wave(m - 5, dur + 0.06, sus=0.5, tau=0.2, lp_hz=2800), t, gain * 0.5, 0.35, send=0.3)


def lead():
    lead_phrase(DROP1, HOOK_A, 4, 0.085)
    lead_phrase(DROP1 + 4 * BAR, HOOK_A, 4, 0.085, harmony=True)
    lead_phrase(DROP2, HOOK_B, 4, 0.085, octave_double=True)
    lead_phrase(DROP2 + 4 * BAR, HOOK_B, 3, 0.09, octave_double=True, harmony=True)


def stabs():
    """Chord stab on each section's downbeat."""
    for t in (8.0, 21.3333, DROP1, DROP2):
        pool = chord(t + 0.01)[2]
        for j, m in enumerate(pool[:5]):
            mix(pluck(m + (12 if j == 4 else 0), 1.2, 0.5), t + 0.006 * j, 0.06, 0.3 + 0.1 * j, send=0.3)


def keys():
    """Breather: gentle electric-piano keys on the 8ths, slow and sparse."""
    r = Rnd(33)
    seq = (0, 2, 3, 2, 4, 3, 2, 1)
    for k in range(int(round(BREATHER / (BEAT / 2))), int(round(65.0 / (BEAT / 2)))):
        t = k * BEAT / 2
        if t < BREATHER or t >= 65.0:
            continue
        i = k - int(round(BREATHER / (BEAT / 2)))
        if r.random() < 0.22:
            continue
        pool = chord(t + 0.01)[2]
        m = pool[seq[i % 8]] + 12
        w = tone(mtof(m), 1.6, ((1.0, 1.0), (2.0, 0.28), (3.0, 0.1), (7.0, 0.03)), attack=0.004, tau=0.55)
        mix(w, t, 0.05 * (1.0 if i % 2 == 0 else 0.7), 0.35 + 0.3 * (i % 2), send=0.5)
    # a low, slow bass note under the breather (soft, no pumping)
    for b in (22, 23, 24):
        t = b * BAR
        mix_bass(bass_wave(chord(t + 0.01)[0] + 12, 14, 0), t, 0.2)


def wind_and_drone():
    rg = Rnd(17)
    d = 6.0

    def cut(u):
        return 0.15 + 0.85 * u * (0.55 + 0.45 * sin(TAU * (1.5 * u * u + 1.3 * u)))

    w = noise_sweep(d, 120, 1900, cut, amp_fn=lambda u: smooth(u * 1.1) ** 1.3, rg=rg)
    mix_moving(w, 2.0, 0.17, pf=lambda u: 0.5 + 0.42 * sin(TAU * (0.7 * u + 0.6 * u * u) * 1.6), send=0.25)
    w2 = noise_sweep(d, 400, 4500, lambda u: u ** 1.6, amp_fn=lambda u: u ** 2.2, rg=rg, hp=500)
    mix_moving(w2, 2.0, 0.09, pf=lambda u: 0.5 + 0.4 * sin(TAU * (1.1 * u + 1.0 * u * u)), send=0.3)
    # low drone: A1 with a fifth and octave creeping in
    dr = tone(55.0, 13.0, ((1.0, 1.0), (2.0, 0.5), (3.0, 0.3), (4.0, 0.14)), attack=6.0, tau=4.5)
    mix(dr, 2.0, 0.17, 0.5)
    dr2 = tone(110.0, 12.0, ((1.0, 1.0), (2.0, 0.25), (3.0, 0.1)), attack=5.5, tau=3.0)
    mix(dr2, 2.0, 0.07, 0.35, send=0.2)
    dr3 = tone(164.81, 11.0, ((1.0, 1.0), (2.0, 0.2)), attack=5.8, tau=2.5)
    mix(dr3, 3.0, 0.045, 0.65, send=0.3)


def ticking():
    """Clock-like ticking texture from 5.333 that speeds up into the impact."""
    t = 5.3333
    i = 0
    while t < 7.98:
        u = (t - 5.3333) / (8.0 - 5.3333)
        mix(WOOD, t, 0.02 + 0.07 * u, 0.3 + 0.4 * (i % 2), send=0.15)
        step = BEAT / 2 if t < 6.667 else S16 if t < 7.667 else S16 / 2
        t += step
        i += 1


def outro_music():
    """Collapse: stuttering, falling plucks and a closing pad; then sparkle after the chord."""
    t = OUTRO + 0.04
    i = 0
    scale = [76, 74, 72, 69, 67, 64, 62, 60, 57]
    while t < CHORD_T - 0.05 and i < len(scale):
        mix(pluck(scale[i], 0.9, 0.4), t, 0.085 * (1 - 0.06 * i), 0.3 + 0.4 * (i % 2), send=0.45)
        t += BEAT * (0.25 + 0.06 * i)
        i += 1
    # after the final chord: sparse major-pentatonic shimmer
    r = Rnd(99)
    pool = (81, 85, 88, 90, 93, 97, 100)
    tt = CHORD_T + 0.35
    while tt < END_T + 0.8:
        m = r.choice(pool)
        mix(bell(mtof(m), 1.6, 0.6), tt, 0.04, r.uniform(0.2, 0.8), send=0.5)
        tt += r.uniform(0.12, 0.3)


# ---------------------------------------------------------------- sound effects
def s_riser(t, u, i):
    d = u - t
    R = Rnd(200 + i)
    long_ = d > 3.0
    hi = 6500 if long_ else 9500
    w = noise_sweep(d, 250, hi, lambda x: x ** (2.0 if long_ else 2.4), rg=R, hp=200 if long_ else 350)
    mix_moving(w, t, 0.34 if long_ else 0.5, pf=lambda x: 0.5 + 0.3 * sin(TAU * (1.0 + 2.5 * x) * x * 2.0), send=0.15)
    rt = rise_tone(d, 150.0 if long_ else 280.0, 1100.0 if long_ else 2600.0, pw=2.0 if long_ else 1.6)
    mix(rt, t, 0.12 if long_ else 0.24, 0.5, send=0.25)
    if not long_:
        rt2 = rise_tone(d, 560.0, 5200.0, pw=2.6, partials=((1.0, 1.0), (1.5, 0.3)))
        mix(rt2, t, 0.06, 0.5, send=0.3)


def s_flutter(t, u, i):
    d = u - t
    R = Rnd(300)
    ticks = []
    for k in range(14):
        n = R.randint(150, 900)
        hp = R.uniform(1500, 5500)
        a = 1 - exp(-TAU * hp / RATE)
        lp = 0.0
        w = zeros(n)
        for j in range(n):
            x = R.random() * 2 - 1
            lp += a * (x - lp)
            w[j] = (x - lp) * exp(-j / (n * 0.28)) * min(1.0, j / 12)
        ticks.append(norm(w))
    tm = 0.0
    while tm < d - 0.02:
        x = tm / d
        env = smooth(x / 0.25) * (1 - smooth((x - 0.82) / 0.18))
        w = R.choice(ticks)
        mix(w, t + tm, 0.26 * env * R.uniform(0.25, 1.0), R.uniform(0.05, 0.95), send=0.06)
        tm += R.uniform(0.005, 0.026) * (1.25 - 0.6 * x)


def s_align(t, u, i):
    R = Rnd(310)
    w = noise_sweep(0.6, 500, 8000, lambda x: smooth(x / 0.8), amp_fn=lambda x: smooth(x / 0.75) * (1 - smooth((x - 0.85) / 0.15)), rg=R, hp=300)
    mix_moving(w, t, 0.4, pf=lambda x: 0.3 + 0.68 * smooth(x / 0.85), send=0.15)
    z = tone(450.0, 0.6, ((1.0, 1.0), (2.0, 0.2)), attack=0.03, tau=0.22, glide_to=2800.0, glide_s=0.5)
    mix_moving(z, t, 0.1, pf=lambda x: 0.3 + 0.68 * smooth(x / 0.85), send=0.2)
    mix(tick_wave(311, 0.03, 0.005, 3000), t + 0.5, 0.45, 0.97)
    mix(tone(1800.0, 0.12, ((1.0, 1.0), (2.4, 0.4)), attack=0.001, tau=0.03), t + 0.5, 0.14, 0.97, send=0.3)


def s_counter(t, u, i):
    d = u - t
    R = Rnd(320)
    ladder = [69, 72, 74, 76, 79, 81, 84, 86, 88, 91, 93, 96]
    tm = 0.0
    while tm < d - 0.01:
        x = tm / d
        m = ladder[min(11, int(x * 12))]
        w = tone(mtof(m), 0.035, ((1.0, 1.0), (3.0, 0.3), (5.0, 0.1)), attack=0.0005, tau=0.007)
        mix(w, t + tm, 0.15 + 0.08 * x, 0.5 + R.uniform(-0.12, 0.12), send=0.08)
        if int(tm * 1000) % 2 == 0:
            mix(WOOD, t + tm, 0.05, 0.5)
        tm += 0.13 * (1 - x) ** 1.7 + 0.011


SUB_IMPACT = None


def tail_noise(seconds, fmax, rg, gain, t, pan_a=0.2, pan_b=0.8, tau_k=5.0):
    """Reverb-like tail: two decorrelated noises that darken as they fade."""
    w = noise_sweep(seconds, 180, fmax, lambda x: exp(-x * tau_k), rg=rg)
    mix_moving(w, t, gain, pan_a, pan_b)
    w2 = noise_sweep(seconds, 180, fmax, lambda x: exp(-x * tau_k), rg=rg)
    mix_moving(w2, t, gain, pan_b, pan_a)


def big_hit(t, gain=1.0, sub=(85.0, 30.0), sub_tau=1.3, crash=True, tail=2.6, seed=0):
    R = Rnd(400 + seed)
    mix(sub_wave(sub[0], sub[1], sub_tau * 3, sub_tau), t, 0.62 * gain, 0.5)
    mix(KICK, t, 0.38 * gain, 0.5)
    nb = hat_wave(410 + seed, 0.35, 0.09, 350)
    mix(nb, t, 0.42 * gain, 0.5, send=0.15)
    if crash:
        mix(CRASH, t, 0.3 * gain, 0.5, send=0.25)
    tail_noise(tail, 3200, R, 0.22 * gain, t)


def s_impact(t, u, i):
    big_hit(t, 1.0, sub=(95.0, 28.0), sub_tau=1.6, tail=3.0, seed=1)
    # low A octave boom to tie the hit to the key
    mix(tone(55.0, 2.5, ((1.0, 1.0), (2.0, 0.4)), attack=0.004, tau=1.0), t, 0.3, 0.5)


def s_sparkle(t, u, i):
    R = Rnd(430 + i)
    pool = [84, 88, 91, 93, 96, 100, 103]
    times = sorted(R.uniform(0, 1.1) for _ in range(13))
    for k, tm in enumerate(times):
        m = pool[R.randint(0, len(pool) - 1)]
        mix(bell(mtof(m), 1.4, 0.32, GLASS_PARTS), t + tm, 0.2 * R.uniform(0.5, 1.0) * (1.0 - 0.3 * k / 13), R.uniform(0.1, 0.9), send=0.45)


def s_toss(t, u, i):
    d = u - t
    soft = BREATHER <= t < DROP2
    R = Rnd(440 + i)
    w = noise_sweep(d, 350, 5200 if not soft else 3200, lambda x: math.sin(math.pi * x) ** 1.2,
                    amp_fn=lambda x: math.sin(math.pi * x) ** 1.5, rg=R, hp=250)
    pf = lambda x: 0.04 + 0.92 * x
    mix_moving(w, t, 0.3 if not soft else 0.2, pf=pf, send=0.2)
    # pitch arc: rises to the apex and falls, like the file
    m = int(d * RATE)
    arc = zeros(m)
    ph = 0.0
    for n in range(m):
        x = n / m
        f = 380 + 720 * math.sin(math.pi * x)
        ph += TAU * f / RATE
        arc[n] = (sin(ph) + 0.2 * sin(2 * ph)) * math.sin(math.pi * x) ** 2
    mix_moving(fade_edges(arc, 44, 441), t, 0.07 if not soft else 0.05, pf=pf, send=0.3)


def s_land(t, u, i):
    mix(tone(130.0, 0.25, ((1.0, 1.0), (2.0, 0.3)), attack=0.002, tau=0.055, glide_to=62.0, glide_s=0.06), t, 0.5, 0.65)
    mix(tick_wave(450, 0.012, 0.003, 3500), t, 0.22, 0.66)
    mix(hat_wave(451, 0.12, 0.03, 900), t, 0.1, 0.62, send=0.1)


def bwomp(f0, f1, secs, vib, vr=6.5):
    key = ("bwomp", f0, f1, secs, vib, vr)
    if key in _cache:
        return _cache[key]
    m = int(secs * RATE)
    out = zeros(m)
    ph = 0.0
    for n in range(m):
        x = n / m
        t = n / RATE
        f = f0 * (f1 / f0) ** smooth(x * 1.15) * (1 + vib * sin(TAU * vr * t))
        ph += TAU * f / RATE
        v = sin(ph) + 0.5 * sin(2 * ph) + 0.3 * sin(3 * ph) + 0.15 * sin(4 * ph)
        out[n] = v * min(1.0, n / 400) * exp(-t / (secs * 0.55))
    _cache[key] = fade_edges(norm(out), 1, 882)
    return _cache[key]


def s_nope(t, u, i):
    f0 = (233.0, 208.0, 185.0)[i % 3]
    a = bwomp(f0, f0 * 0.66, 0.36 + 0.03 * i, 0.012 * (i + 1))
    b = bwomp(f0 * 0.85, f0 * 0.44, 0.62 + 0.05 * i, 0.03 + 0.012 * i, vr=6.0 + i)
    mix(a, t, 0.36, 0.5 - 0.06 * (i % 3), send=0.12)
    mix(b, t + 0.22 + 0.01 * i, 0.4, 0.5 + 0.06 * (i % 3), send=0.12)
    mix(tick_wave(470 + i, 0.012, 0.003, 1500), t, 0.12, 0.5)


def s_point(t, u, i):
    mix(bell(mtof(93), 1.6, 0.8), t, 0.38, 0.62, send=0.4)
    mix(bell(mtof(100), 1.2, 0.5), t + 0.05, 0.22, 0.7, send=0.4)
    mix(bell(mtof(81), 1.4, 0.7), t, 0.22, 0.45, send=0.3)
    mix(tick_wave(480, 0.02, 0.004, 4000), t, 0.15, 0.6)


def s_buzz(t, u, i):
    r = Rnd(131)
    m = int(0.64 * RATE)
    car = zeros(m)
    rat = zeros(m)
    a1 = 1 - exp(-TAU * 1300 / RATE)
    a2 = 1 - exp(-TAU * 260 / RATE)
    lp1 = lp2 = ph = 0.0

    def pulse(tt, a, b):
        return smooth((tt - a) / 0.01) * (1 - smooth((tt - b + 0.03) / 0.03))

    for n in range(m):
        tt = n / RATE
        e = pulse(tt, 0.0, 0.24) + pulse(tt, 0.34, 0.58)
        am = 0.55 + 0.45 * sin(TAU * 52 * tt)
        x = r.random() * 2 - 1
        lp1 += a1 * (x - lp1)
        lp2 += a2 * (x - lp2)
        ph += TAU * (96 + 6 * sin(TAU * 9 * tt)) / RATE
        saw = sum(sin(h * ph) / h for h in range(1, 7))
        knock = 0.0
        for t0 in (0.0, 0.34):
            if tt >= t0:
                knock += sin(TAU * 170 * tt) * exp(-(tt - t0) / 0.02)
        car[n] = e * (am * saw * 0.5 + knock * 0.9)
        rat[n] = e * am * (lp1 - lp2)
    car, rat = norm(car), norm(rat)
    out = array.array("d", [0.65 * a + 0.45 * b for a, b in zip(car, rat)])
    mix(fade_edges(norm(out), 22, 441), t, 0.6, 0.4, send=0.08)


CHAT_PAIRS = ((88, 93), (91, 96))


def s_chat(t, u, i):
    a, b = CHAT_PAIRS[i % 2]
    for j, m in enumerate((a, b)):
        mix(bell(mtof(m), 1.4, 0.32), t + j * 0.13, 0.3, 0.62, send=0.35)
    mix(pluck(a - 12, 0.7, 0.4), t, 0.14, 0.6, send=0.2)
    mix(tone(mtof(a - 24), 0.12, attack=0.002, tau=0.03), t, 0.2, 0.6)  # soft "pop" on arrival


def s_ping(t, u, i):
    m = (76, 81, 84)[i % 3]
    w = tone(mtof(m), 2.2, ((1.0, 1.0), (2.0, 0.07)), attack=0.003, tau=0.4, glide_to=mtof(m) * 1.012, glide_s=0.02)
    pan = (0.28, 0.72, 0.5)[i % 3]
    for k in range(5):
        mix(w, t + k * BEAT / 2, 0.36 * 0.55 ** k, pan if k % 2 == 0 else 1 - pan, send=0.15)
    mix(bell(mtof(m + 12), 1.0, 0.25), t, 0.1, pan, send=0.3)
    mix(tick_wave(490 + i, 0.012, 0.002, 4000), t, 0.12, pan)


def s_pop(t, u, i):
    base = (64, 68, 72)[i % 3]
    w = tone(mtof(base), 0.22, ((1.0, 1.0), (2.0, 0.25)), attack=0.003, tau=0.05, glide_to=mtof(base + 16), glide_s=0.045)
    mix(w, t, 0.38, 0.4 + 0.1 * i, send=0.25)
    mix(tone(mtof(base + 24), 0.1, attack=0.001, tau=0.02), t + 0.045, 0.1, 0.5 + 0.08 * i, send=0.3)
    mix(tick_wave(500 + i, 0.01, 0.002, 4000), t, 0.15, 0.45)


_swish_count = [0]


def s_swish(t, u, i):
    k = _swish_count[0]
    _swish_count[0] += 1
    left = k % 2 == 0
    R = Rnd(510 + k)
    w = noise_sweep(0.32, 1400, 7500, lambda x: smooth(x / 0.45), amp_fn=lambda x: smooth(x / 0.4) * (1 - smooth((x - 0.45) / 0.55)), rg=R, hp=700)
    p0, p1 = (0.1, 0.62) if left else (0.9, 0.38)
    mix_moving(w, t, 0.3, p0, p1, send=0.15)
    ladder = (69, 72, 74, 76, 79, 81, 84)
    m = ladder[min(k, 6)]
    mix(tone(mtof(m + 12), 0.3, ((1.0, 1.0), (2.0, 0.2)), attack=0.002, tau=0.07), t + 0.22, 0.14, p1, send=0.3)
    mix(tick_wave(520 + k, 0.012, 0.003, 2500), t + 0.22, 0.12, p1)


def s_drop(t, u, i):
    # reverse cymbal: rising noise that ends exactly at t
    m = int(1.4 * RATE)
    R = Rnd(530 + i)
    rc = noise_sweep(1.4, 2500, 11000, lambda x: x ** 2.2, amp_fn=lambda x: x ** 3.0, rg=R, hp=3000)
    s0 = at(t) - len(rc)
    mix_moving(rc, 0, 0.3, 0.4, 0.6, send=0.2, s=s0)
    # a breath of silence in the music is handled by the arrangement (drums stop before the drop)
    big_hit(t, 1.25, sub=(75.0, 27.0), sub_tau=1.5, tail=3.0, seed=10 + i)
    mix(tone(55.0, 2.5, ((1.0, 1.0), (2.0, 0.35)), attack=0.004, tau=1.0), t, 0.26, 0.5)
    # stab accent on the new section
    for j, mm in enumerate((57, 64, 69, 72, 76)):
        mix(pluck(mm, 1.6, 0.5), t + 0.008 * j, 0.14, 0.25 + 0.12 * j, send=0.4)


def s_type(t, u, i):
    d = u - t
    R = Rnd(540 + i)
    keys = [tick_wave(550 + j, R.choice((0.012, 0.016, 0.02)), 0.0025, R.choice((1800, 2500, 3200))) for j in range(6)]
    thud = [tone(R.uniform(150, 230), 0.04, attack=0.0008, tau=0.011) for _ in range(4)]
    tm = 0.0
    while tm < d - 0.12:
        for _ in range(R.randint(3, 8)):
            if tm >= d - 0.12:
                break
            g = R.uniform(0.5, 1.0)
            mix(R.choice(keys), t + tm, 0.42 * g, 0.42 + R.uniform(-0.05, 0.12))
            mix(R.choice(thud), t + tm, 0.11 * g, 0.45)
            tm += R.uniform(0.04, 0.115)
        tm += R.uniform(0.1, 0.25)
    # enter: a deeper click
    te = max(0.0, d - 0.06)
    mix(tick_wave(560, 0.03, 0.006, 1500), t + te, 0.5, 0.46)
    mix(tone(110.0, 0.12, ((1.0, 1.0), (2.0, 0.3)), attack=0.001, tau=0.03), t + te, 0.22, 0.46)


def s_handshake(t, u, i):
    g = 0.9
    lo = tone(mtof(57), 1.6, ((1.0, 1.0), (2.0, 0.3), (3.0, 0.1)), attack=0.03, tau=1.2, glide_to=mtof(69), glide_s=g)
    hi = tone(mtof(81), 1.6, ((1.0, 1.0), (2.0, 0.2), (3.0, 0.06)), attack=0.03, tau=1.2, glide_to=mtof(69), glide_s=g)
    mix_moving(lo, t, 0.22, 0.04, 0.5, send=0.2, pf=lambda x: 0.04 + 0.46 * smooth(x * 1.6 / 0.9 * 0.9))
    mix_moving(hi, t, 0.17, 0.96, 0.5, send=0.2, pf=lambda x: 0.96 - 0.46 * smooth(x * 1.6 / 0.9 * 0.9))
    mix(tick_wave(570, 0.02, 0.004, 3000), t, 0.25, 0.04)
    mix(tick_wave(571, 0.02, 0.004, 3000), t, 0.25, 0.96)
    tm = t + g
    mix(bell(mtof(81), 2.0, 0.9), tm, 0.36, 0.5, send=0.4)
    mix(bell(mtof(88), 2.0, 0.7), tm, 0.22, 0.4, send=0.4)
    mix(bell(mtof(85), 2.0, 0.6), tm + 0.04, 0.18, 0.6, send=0.4)
    mix(tick_wave(572, 0.03, 0.005, 2500), tm, 0.35, 0.5)
    for j, m in enumerate((57, 64, 69, 73)):
        mix(pluck(m, 1.2, 0.5), tm, 0.13, 0.3 + 0.13 * j, send=0.3)


def s_lock(t, u, i):
    mix(tick_wave(580, 0.03, 0.006, 2500), t, 0.55, 0.5)
    mix(tone(1250.0, 0.16, ((1.0, 1.0), (2.4, 0.5), (5.1, 0.2)), attack=0.001, tau=0.035), t, 0.18, 0.5, send=0.2)
    mix(tick_wave(581, 0.03, 0.005, 1800), t + 0.045, 0.4, 0.5)
    mix(tone(mtof(40), 0.3, ((1.0, 1.0), (2.0, 0.35), (3.0, 0.1)), attack=0.002, tau=0.07, glide_to=mtof(32), glide_s=0.06), t + 0.08, 0.75, 0.5)
    mix(bell(mtof(93), 1.0, 0.25), t + 0.08, 0.09, 0.5, send=0.4)


def s_dialog(t, u, i):
    w = tone(mtof(69), 0.3, ((1.0, 1.0), (2.0, 0.2)), attack=0.006, tau=0.08, glide_to=mtof(81), glide_s=0.05)
    mix(w, t, 0.34, 0.5, send=0.3)
    mix(tone(mtof(88), 0.3, attack=0.004, tau=0.07), t + 0.07, 0.1, 0.5, send=0.3)
    mix(bell(mtof(93), 0.8, 0.2), t + 0.07, 0.08, 0.55, send=0.4)


def s_click(t, u, i):
    tk = tick_wave(590, 0.02, 0.003, 2500)
    mix(tk, t, 0.6, 0.5)
    mix(tone(1200.0, 0.03, attack=0.001, tau=0.008), t, 0.16, 0.5)
    mix(tone(300.0, 0.04, attack=0.001, tau=0.01), t, 0.14, 0.5)
    mix(tk, t + 0.07, 0.34, 0.5)


def s_slam(t, u, i):
    big_hit(t, 1.15, sub=(70.0, 27.0), sub_tau=1.0, crash=True, tail=2.0, seed=20 + i)
    R = Rnd(600 + i)
    # distorted transient: noise + body through a hard tanh
    m = int(0.25 * RATE)
    dist = zeros(m)
    ph = 0.0
    for n in range(m):
        x = n / RATE
        ph += TAU * (60 + 260 * exp(-x / 0.02)) / RATE
        dist[n] = math.tanh(6.0 * (0.9 * sin(ph) + 0.6 * (R.random() * 2 - 1)) * exp(-x / 0.05))
    mix(fade_edges(norm(dist), 1, 441), t, 0.42, 0.5, send=0.12)
    mix(SNARE, t, 0.42, 0.5, send=0.25)
    mix(CLAP, t, 0.25, 0.5, send=0.3)
    # cards flying: a scatter of papery ticks
    for k in range(18):
        w = tick_wave(610 + k, R.choice((0.02, 0.03)), 0.005, R.uniform(1800, 5000))
        mix(w, t + 0.03 + k * R.uniform(0.012, 0.03), 0.16 * (1 - k / 22), R.uniform(0.05, 0.95))


def s_split(t, u, i):
    R = Rnd(620)
    for k, tm in enumerate((0.0, 0.028, 0.085, 0.16, 0.24, 0.31)):
        w = hat_wave(630 + k, 0.05, 0.007 + 0.004 * R.random(), R.uniform(2500, 6000))
        mix(w, t + tm, 0.5 * (1 - 0.08 * k), 0.15 + 0.14 * k, send=0.15)
    mix(hat_wave(640, 0.25, 0.05, 3000), t, 0.3, 0.5, send=0.2)
    for tm in (0.04, 0.11, 0.2):
        f = R.uniform(2800, 5200)
        mix(bell(f, 0.5, 0.12, GLASS_PARTS), t + tm, 0.14, R.uniform(0.2, 0.8), send=0.4)
    mix(tone(90.0, 0.25, attack=0.002, tau=0.05), t, 0.3, 0.5)


def s_stream(t, u, i):
    d = u - t
    ladder = [72, 76, 79, 81, 84, 88, 91]
    tm = 0.0
    k = 0
    while tm < d - 0.01:
        x = tm / d
        m = ladder[(k * 2 + k // 7) % 7]
        w = tone(mtof(m), 0.1, ((1.0, 1.0), (2.0, 0.25), (3.0, 0.08)), attack=0.0008, tau=0.018)
        mix(w, t + tm, 0.26, 0.05 + 0.9 * x, send=0.2)
        mix(WOOD, t + tm, 0.08, 0.05 + 0.9 * x)
        tm += BEAT / 8 * (1.0 - 0.3 * x)
        k += 1


def s_assemble(t, u, i):
    R = Rnd(650)
    w = noise_sweep(0.32, 600, 9000, lambda x: x ** 1.5, amp_fn=lambda x: x ** 2.0, rg=R, hp=800)
    mix_moving(w, t, 0.34, 0.85, 0.5, send=0.15)
    mix(tone(400.0, 0.35, ((1.0, 1.0), (2.0, 0.2)), attack=0.1, tau=10.0, glide_to=2200.0, glide_s=0.3), t, 0.1, 0.5, send=0.2)
    tc = t + 0.32
    mix(tick_wave(651, 0.03, 0.005, 2500), tc, 0.6, 0.5)
    mix(tone(1000.0, 0.15, ((1.0, 1.0), (2.4, 0.4)), attack=0.001, tau=0.03), tc, 0.2, 0.5, send=0.25)
    mix(tone(mtof(45), 0.2, attack=0.002, tau=0.05), tc, 0.25, 0.5)


def s_check(t, u, i):
    for m, g, tau in ((81, 0.34, 1.2), (85, 0.3, 1.1), (88, 0.3, 1.0), (93, 0.24, 0.9), (97, 0.14, 0.7)):
        mix(bell(mtof(m), 2.6, tau), t + 0.012 * (m - 81) / 4, g, 0.3 + 0.4 * ((m - 81) % 5) / 4, send=0.45)
    for j, m in enumerate((57, 64, 69, 73, 76)):
        mix(pluck(m, 1.6, 0.5), t, 0.12, 0.25 + 0.12 * j, send=0.35)
    mix(tone(mtof(45), 2.0, ((1.0, 1.0), (2.0, 0.3)), attack=0.01, tau=0.8), t, 0.26, 0.5)
    mix(tick_wave(660, 0.02, 0.004, 4000), t, 0.2, 0.5)


def s_ticks(t, u, i):
    d = u - t
    ladder = [69, 72, 74, 76, 79, 81, 84, 86, 88, 91, 93, 96]
    n = int(d / 0.1)
    for k in range(n):
        x = k / max(1, n - 1)
        m = ladder[min(11, int(x * 11.99))]
        w = tone(mtof(m), 0.05, ((1.0, 1.0), (3.0, 0.25), (5.0, 0.1)), attack=0.0005, tau=0.011)
        mix(w, t + k * 0.1, 0.22, 0.55 + 0.25 * x, send=0.15)
        mix(WOOD, t + k * 0.1, 0.06, 0.5)


def s_breath(t, u, i):
    R = Rnd(670)
    w = noise_sweep(1.4, 150, 7000, lambda x: 1 - smooth(x * 1.05), amp_fn=lambda x: math.sin(math.pi * min(1.0, x * 1.3 + 0.1)) ** 0.7 * (1 - x * 0.4), rg=R, hp=100)
    mix_moving(w, t, 0.3, 0.3, 0.7, send=0.3)
    mix(tone(700.0, 1.2, ((1.0, 1.0), (2.0, 0.2)), attack=0.02, tau=0.5, glide_to=130.0, glide_s=1.0), t, 0.1, 0.5, send=0.4)
    mix(tone(mtof(45), 2.5, ((1.0, 1.0), (2.0, 0.3)), attack=0.01, tau=1.0), t, 0.3, 0.5)
    mix(hat_wave(671, 1.5, 0.4, 5000), t, 0.05, 0.5, send=0.3)


def s_reveal(t, u, i):
    mix(bell(mtof(81), 3.0, 1.2), t, 0.3, 0.45, send=0.5)
    mix(bell(mtof(88), 3.0, 1.0), t + 0.03, 0.22, 0.58, send=0.5)
    mix(bell(mtof(93), 2.5, 0.8), t + 0.07, 0.12, 0.5, send=0.5)
    R = Rnd(680)
    w = noise_sweep(1.6, 300, 4500, lambda x: math.sin(math.pi * x), rg=R, hp=500)
    mix_moving(w, t - 0.1, 0.08, 0.6, 0.4, send=0.3)


def s_qr(t, u, i):
    d = u - t
    R = Rnd(690)
    pool = (81, 84, 86, 88, 91, 93, 96, 98)
    step = 0.0583
    k = 0
    while k * step < d - 0.02:
        x = k * step / d
        if k == 0 or R.random() < 0.68:
            m = R.choice(pool)
            w = crush(tone(mtof(m), 0.05, ((1.0, 1.0), (3.0, 0.15), (5.0, 0.05)), attack=0.0005, tau=0.012), 3, 5)
            mix(w, t + k * step, 0.22, 0.12 + 0.76 * x + R.uniform(-0.04, 0.04), send=0.18)
        k += 1


def s_scan(t, u, i):
    d = 0.8
    w = tone(300.0, 0.95, ((1.0, 1.0), (3.0, 0.15)), attack=0.06, tau=30.0, glide_to=2200.0, glide_s=d)
    mix_moving(w, t, 0.2, pf=lambda x: 0.5 + 0.45 * sin(TAU * 1.0 * x), send=0.2)
    R = Rnd(700)
    nz = noise_sweep(0.85, 1500, 8000, lambda x: x, amp_fn=lambda x: smooth(x / 0.9) * 0.5, rg=R, hp=1500)
    mix_moving(nz, t, 0.15, pf=lambda x: 0.5 + 0.45 * sin(TAU * 1.0 * x), send=0.2)
    mix(tone(mtof(100), 0.14, ((1.0, 1.0), (2.0, 0.15)), attack=0.002, tau=0.05), t + d, 0.35, 0.5, send=0.3)


def s_confirm(t, u, i):
    for j, m in enumerate((81, 88)):
        mix(bell(mtof(m), 1.5, 0.5), t + j * 0.11, 0.38, 0.45 + 0.1 * j, send=0.4)
        mix(pluck(m - 12, 0.8, 0.45), t + j * 0.11, 0.14, 0.45 + 0.1 * j, send=0.3)
    mix(bell(mtof(100), 1.0, 0.3), t + 0.11, 0.14, 0.6, send=0.4)
    mix(tick_wave(710, 0.02, 0.004, 4000), t, 0.15, 0.5)


def s_relay(t, u, i):
    R = Rnd(720 + i)
    w = noise_sweep(1.1, 300, 4200, lambda x: smooth(x / 0.5) * (1 - 0.6 * smooth((x - 0.5) / 0.5)),
                    amp_fn=lambda x: math.sin(math.pi * x) ** 1.3, rg=R, hp=300)
    mix_moving(w, t, 0.3, 0.06, 0.94, send=0.2)
    # Doppler-like whistle: pitch drops as the packet passes the tower
    m = int(1.1 * RATE)
    wh = zeros(m)
    ph = 0.0
    for n in range(m):
        x = n / m
        f = 1500 - 650 * smooth((x - 0.35) / 0.3)
        ph += TAU * f / RATE
        wh[n] = sin(ph) * math.sin(math.pi * x) ** 2
    mix_moving(fade_edges(wh, 44, 441), t, 0.07, 0.06, 0.94, send=0.25)
    mix(tick_wave(730, 0.02, 0.004, 3500), t + 0.55, 0.4, 0.5)
    mix(bell(mtof((88, 91, 93)[i % 3]), 1.2, 0.3), t + 0.55, 0.22, 0.5, send=0.4)
    mix(pluck((57, 60, 64)[i % 3], 0.8, 0.45), t, 0.11, 0.1, send=0.25)
    mix(pluck((72, 76, 79)[i % 3], 0.8, 0.45), t + 1.0, 0.11, 0.9, send=0.25)


def s_stickers(t, u, i):
    R = Rnd(740)
    ladder = [67, 69, 72, 74, 76, 79, 81, 84, 86, 88]
    for k, ts in enumerate(TL["stickerTimes"]):
        x = k / max(1, len(TL["stickerTimes"]) - 1)
        pan = 0.2 + 0.6 * ((k * 3) % 5) / 4
        sl = noise_sweep(0.06, 1500, 8000, lambda q: 1 - 0.6 * q, amp_fn=lambda q: (1 - q) ** 1.5, rg=R, hp=900)
        mix(sl, ts, 0.42, pan, send=0.1)
        mix(tone(240.0, 0.12, ((1.0, 1.0), (2.0, 0.3)), attack=0.001, tau=0.03, glide_to=110.0, glide_s=0.05), ts, 0.4, pan)
        mix(tone(mtof(ladder[k]), 0.3, ((1.0, 1.0), (2.0, 0.3), (3.0, 0.1)), attack=0.001, tau=0.08), ts, 0.22 + 0.1 * x, pan, send=0.3)
        mix(bell(mtof(ladder[k] + 12), 0.8, 0.22), ts + 0.012, 0.1 + 0.05 * x, 1 - pan, send=0.4)
        mix(tick_wave(750 + k, 0.012, 0.002, 4000), ts, 0.25, pan)


def s_whoosh(t, u, i):
    d = 2.3
    R = Rnd(760)
    spin = lambda x: 0.5 + 0.42 * sin(TAU * (0.9 * x * 2.3 + 2.4 * x * x * 2.3))
    env = lambda x: (x / 0.38) ** 2.4 if x < 0.38 else 1 - smooth((x - 0.38) / 0.62) * 0.97
    for k in range(2):
        w = noise_sweep(d, 150, 6500, env, rg=R, hp=120)
        mix_moving(w, t, 0.3, pf=(spin if k == 0 else (lambda x: 1 - spin(x))), send=0.2)
    mix(rise_tone(0.9, 200.0, 1600.0, pw=1.3), t, 0.12, 0.5, send=0.3)
    mix(tone(1600.0, 1.4, ((1.0, 1.0), (2.0, 0.15)), attack=0.01, tau=0.45, glide_to=520.0, glide_s=1.2), t + 0.9, 0.09, 0.5, send=0.4)


def s_collapse(t, u, i):
    d = CHORD_T - t
    R = Rnd(770)
    w = noise_sweep(d, 120, 4500, lambda x: x ** 1.4, amp_fn=lambda x: x ** 2.0, rg=R, hp=150)
    mix_moving(w, t, 0.34, 0.25, 0.75, send=0.2)
    rv = rise_tone(d, 55.0, 330.0, pw=1.6)
    mix(rv, t, 0.22, 0.5, send=0.2)
    # thump lands exactly on the chord time
    mix(sub_wave(62.0, 30.0, 1.2, 0.35, 0.05), CHORD_T, 0.5, 0.5)
    mix(KICK, CHORD_T, 0.3, 0.5)


def s_chord(t, u, i):
    voices = ((45, 0.1, 0.5), (57, 0.09, 0.3), (64, 0.08, 0.7), (69, 0.08, 0.4), (73, 0.07, 0.6), (76, 0.06, 0.35), (83, 0.04, 0.65))
    for j, (m, g, p) in enumerate(voices):
        for det, pp in ((0.0, p), (0.003, 1 - p)):
            w = tone(mtof(m) * (1 + det), 2.8, ((1.0, 1.0), (2.0, 0.3), (3.0, 0.1)), attack=0.04, tau=2.4)
            mix(w, t, g * 0.75, pp, send=0.3)
    for j, m in enumerate((57, 64, 69, 73, 76, 81, 85, 88)):
        mix(pluck(m, 2.0, 0.5), t + 0.022 * j, 0.11, 0.2 + 0.08 * j, send=0.4)
    for j, m in enumerate((93, 97, 100)):
        mix(bell(mtof(m), 2.7, 1.2), t + 0.05 + 0.04 * j, 0.11, 0.3 + 0.2 * j, send=0.5)
    R = Rnd(780)
    w = noise_sweep(1.6, 200, 5000, lambda x: math.sin(math.pi * x) ** 0.8, amp_fn=lambda x: math.sin(math.pi * x) ** 1.4, rg=R, hp=300)
    mix_moving(w, t - 0.2, 0.14, 0.3, 0.7, send=0.3)
    mix(tone(mtof(33), 2.6, ((1.0, 1.0), (2.0, 0.3)), attack=0.02, tau=1.5), t, 0.35, 0.5)


def s_end(t, u, i):
    R = Rnd(790)
    w = noise_sweep(1.5, 150, 4200, lambda x: 1 - smooth(x), amp_fn=lambda x: math.sin(math.pi * x * 0.9) ** 1.2, rg=R, hp=200)
    mix_moving(w, t, 0.1, 0.6, 0.4, send=0.3)
    mix(bell(mtof(93), 1.5, 0.7), t + 0.1, 0.06, 0.55, send=0.5)


HANDLERS = {
    "riser": s_riser, "flutter": s_flutter, "align": s_align, "counter": s_counter, "impact": s_impact,
    "sparkle": s_sparkle, "toss": s_toss, "land": s_land, "nope": s_nope, "point": s_point, "buzz": s_buzz,
    "chat": s_chat, "ping": s_ping, "pop": s_pop, "swish": s_swish, "drop": s_drop, "type": s_type,
    "handshake": s_handshake, "lock": s_lock, "dialog": s_dialog, "click": s_click, "slam": s_slam,
    "split": s_split, "stream": s_stream, "assemble": s_assemble, "check": s_check, "ticks": s_ticks,
    "breath": s_breath, "reveal": s_reveal, "qr": s_qr, "scan": s_scan, "confirm": s_confirm,
    "relay": s_relay, "stickers": s_stickers, "whoosh": s_whoosh, "collapse": s_collapse,
    "chord": s_chord, "end": s_end,
}


# ---------------------------------------------------------------- score
render_pad()
drums()
snare_rolls()
bass_line()
arps()
lead()
stabs()
keys()
wind_and_drone()
ticking()
outro_music()

cue_log = []
counts = {}
for c in TL["cues"]:
    kind = c["kind"]
    t_ = float(c["t"])
    u_ = float(c["until"]) if "until" in c else None
    i_ = counts.get(kind, 0)
    counts[kind] = i_ + 1
    HANDLERS[kind](t_, u_, i_)
    cue_log.append((kind, t_, at(t_)))
missing = {c["kind"] for c in TL["cues"]} - set(HANDLERS)
assert not missing, missing

# ---------------------------------------------------------------- final pass
pad_level = curve([(0, 0.0), (2.0, 0.0), (8.0, 0.75), (8.01, 0.9), (21.3333, 0.9), (37.0, 1.25), (DROP1, 1.15),
                   (BREATHER - 0.2, 1.15), (BREATHER + 0.5, 1.2), (65.0, 1.25), (DROP2, 1.15),
                   (OUTRO, 1.15), (CHORD_T - 0.2, 0.55), (CHORD_T + 0.05, 1.3), (DUR, 1.0)])
pad_cut = curve([(0, 300), (2, 300), (8, 900), (21.3333, 800), (37.0, 5200), (DROP1, 4200), (BREATHER - 0.1, 4200),
                 (BREATHER + 1.0, 1500), (65.0, 2000), (DROP2 - 0.05, 6000), (DROP2, 5200), (OUTRO, 5200),
                 (CHORD_T - 0.1, 450), (CHORD_T + 0.1, 6500), (DUR, 4500)])
duck_depth = curve([(0, 0.0), (21.3333, 0.0), (21.4, 0.22), (36.0, 0.32), (DROP1 - 0.01, 0.0), (DROP1, 0.58),
                    (BREATHER - 0.05, 0.58), (BREATHER, 0.0), (DROP2 - 0.01, 0.0), (DROP2, 0.58), (OUTRO - 0.02, 0.58), (OUTRO, 0.0)])
bass_gain = curve([(0, 1.0), (DUR, 1.0)])
FADE_S = DUR - END_T


def fade(t):
    if t >= DUR:
        return 0.0
    if t <= END_T:
        return 1.0
    return 0.5 * (1 + cos(math.pi * (t - END_T) / FADE_S))


DIP_LEN = int(0.3 * RATE)
DIP = [max(0.0, 1 - j / DIP_LEN) ** 1.7 for j in range(BEAT_N)]
D = int(round(0.75 * BEAT * RATE))  # dotted 8th ping-pong delay
FB, WET = 0.4, 0.55
a_damp = 1 - exp(-TAU * 2600 / RATE)
a_top = 1 - exp(-TAU * 12000 / RATE)
R_HP = exp(-TAU * 28 / RATE)
ringL, ringR = zeros(D), zeros(D)
outL, outR = zeros(N), zeros(N)
pl = pr = fl = fr = 0.0
xl1 = xr1 = hl = hr = ml = mr = 0.0
k = 0
for b0 in range(0, N, BLK):
    b1 = min(b0 + BLK, N)
    t = b0 / RATE
    ap = 1 - exp(-TAU * pad_cut(t) / RATE)
    pg = pad_level(t)
    dd = duck_depth(t)
    fd0, fd1 = fade(t), fade(b1 / RATE)
    dfd = (fd1 - fd0) / (b1 - b0)
    fd = fd0
    j = b0 % BEAT_N
    for n in range(b0, b1):
        pl += ap * (padL[n] - pl)
        pr += ap * (padR[n] - pr)
        dip = DIP[j]
        j += 1
        if j == BEAT_N:
            j = 0
        g = pg * (1 - dd * dip)
        gb = 1 - 0.85 * dd * dip
        wl = ringL[k]
        wr = ringR[k]
        fl += a_damp * (wl - fl)
        fr += a_damp * (wr - fr)
        sm_ = sendM[n]
        ringL[k] = sm_ * 0.8 + FB * fr
        ringR[k] = sm_ * 0.3 + FB * fl
        k += 1
        if k == D:
            k = 0
        bv = bassM[n] * gb
        xl = pl * g + bv + dryL[n] + WET * wl
        xr = pr * g + bv + dryR[n] + WET * wr
        hl = R_HP * (hl + xl - xl1)
        hr = R_HP * (hr + xr - xr1)
        xl1, xr1 = xl, xr
        ml += a_top * (hl - ml)
        mr += a_top * (hr - mr)
        outL[n] = ml * fd
        outR[n] = mr * fd
        fd += dfd

# ---- look-ahead peak limiter (64-sample blocks, 12-block look-ahead)
peak0 = max(max(outL), -min(outL), max(outR), -min(outR)) or 1.0
thr = 0.5 * peak0
LB = 64
nb = (N + LB - 1) // LB
req = []
for b in range(nb):
    sl = slice(b * LB, (b + 1) * LB)
    pk = max(max(outL[sl]), -min(outL[sl]), max(outR[sl]), -min(outR[sl]))
    req.append(min(1.0, thr / pk) if pk > 0 else 1.0)
LA = 12
tgt = [min(req[b:b + LA]) for b in range(nb)]
rel = 1 - exp(-LB / (0.12 * RATE))
gains = []
gcur = 1.0
for b in range(nb):
    if tgt[b] < gcur:
        gcur += (tgt[b] - gcur) * 0.45
        gcur = max(gcur, tgt[b]) if tgt[b] > gcur * 0.0 else gcur
    else:
        gcur += (tgt[b] - gcur) * rel
    gains.append(min(gcur, req[b]) if req[b] < gcur else gcur)
limL, limR = zeros(N), zeros(N)
gprev = 1.0
for b in range(nb):
    a0, a1 = b * LB, min((b + 1) * LB, N)
    g1 = gains[b]
    dg = (g1 - gprev) / (a1 - a0)
    ramp = [gprev + dg * (q + 1) for q in range(a1 - a0)]
    limL[a0:a1] = array.array("d", [x * y for x, y in zip(outL[a0:a1], ramp)])
    limR[a0:a1] = array.array("d", [x * y for x, y in zip(outR[a0:a1], ramp)])
    gprev = g1
limL[N - 1] = limR[N - 1] = 0.0

# gentle tanh for any leftover spikes, then peak-normalise to -1.5 dBFS
DRIVE = 1.15
peak = max(max(limL), -min(limL), max(limR), -min(limR)) or 1.0
knee = math.tanh(DRIVE)
fL = [math.tanh(DRIVE * x / peak) / knee for x in limL]
fR = [math.tanh(DRIVE * x / peak) / knee for x in limR]
peak2 = max(max(fL), -min(fL), max(fR), -min(fR)) or 1.0
scale = 10 ** (-1.5 / 20) * 32767 / peak2
pcm = array.array("h", bytes(4 * N))
pcm[0::2] = array.array("h", [round(x * scale) for x in fL])
pcm[1::2] = array.array("h", [round(x * scale) for x in fR])
if sys.byteorder == "big":
    pcm.byteswap()
out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "web", "reel", "film.wav")
os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
with wave.open(out_path, "wb") as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(RATE)
    w.writeframes(pcm.tobytes())

# ---- report
print(f"wrote {out_path}: {N / RATE:.3f}s, {RATE} Hz 16-bit stereo, {time.time() - T_START:.1f}s to render")
print(f"peak {20 * math.log10(max(abs(v) for v in pcm) / 32767):.2f} dBFS")
seg = int(round(BAR * RATE))
print("RMS per bar (dBFS):")
for a in range(0, N, seg):
    b = min(a + seg, N)
    s = 0.0
    for v in pcm[2 * a:2 * b]:
        s += v * v
    rms = math.sqrt(s / max(1, 2 * (b - a))) / 32767
    print(f"  {a / RATE:6.2f}-{b / RATE:6.2f}s  {20 * math.log10(rms) if rms > 0 else -99.0:6.1f}")
for kind, t_, s_ in cue_log:
    print(f"  cue {kind:<10} {t_:8.4f}s -> sample {s_}")
